import { defineCategory } from './catalog-helpers.js';

export const DRINK_ITEMS = defineCategory("drink", [
  ["water_bottle", "Water Bottle", "water", 500, 12, 250, "legal", {"hydration":22}, ["water bottle"], "water_bottle_small.png"],
  ["large_water_bottle", "Large Water Bottle", "water", 1000, 12, 400, "legal", {"hydration":38}, ["large water bottle"], "water_bottle_big.png"],
  ["sparkling_water", "Sparkling Water", "water", 500, 12, 350, "legal", {"hydration":20}, ["sparkling water"], "water.png"],
  ["cola", "Cola", "soft_drink", 355, 12, 350, "legal", {"hydration":10,"energy":3}, ["cola soda"], null],
  ["diet_cola", "Diet Cola", "soft_drink", 355, 12, 350, "legal", {"hydration":10}, ["diet cola"], null],
  ["orange_soda", "Orange Soda", "soft_drink", 355, 12, 350, "legal", {"hydration":10,"energy":2}, ["orange soda"], null],
  ["lemon_soda", "Lemon Soda", "soft_drink", 355, 12, 350, "legal", {"hydration":10}, ["lemon soda"], null],
  ["energy_drink", "Energy Drink", "energy", 500, 12, 650, "legal", {"hydration":8,"energy":16,"stress":4}, ["energy drink"], null],
  ["sports_drink", "Sports Drink", "energy", 500, 12, 550, "legal", {"hydration":18,"energy":6}, ["sports drink"], null],
  ["coffee", "Coffee", "hot_drink", 350, 12, 450, "legal", {"hydration":5,"energy":10}, ["coffee cup"], null],
  ["espresso", "Espresso", "hot_drink", 90, 12, 350, "legal", {"energy":9}, ["espresso"], null],
  ["latte", "Latte", "hot_drink", 420, 12, 600, "legal", {"hydration":7,"energy":8,"satiety":2}, ["latte"], null],
  ["tea", "Tea", "hot_drink", 350, 12, 400, "legal", {"hydration":9,"stress":-3}, ["tea cup"], null],
  ["hot_chocolate", "Hot Chocolate", "hot_drink", 400, 12, 650, "legal", {"hydration":6,"satiety":4,"stress":-2}, ["hot chocolate"], null],
  ["orange_juice", "Orange Juice", "juice", 500, 12, 550, "legal", {"hydration":15,"energy":2}, ["orange juice"], null],
  ["apple_juice", "Apple Juice", "juice", 500, 12, 550, "legal", {"hydration":15,"energy":2}, ["apple juice"], null],
  ["milk", "Milk", "dairy", 1000, 12, 500, "legal", {"hydration":10,"satiety":5}, ["milk carton"], null],
  ["beer", "Beer", "alcohol", 500, 12, 650, "legal", {"hydration":-2,"stress":-5}, ["beer bottle"], "beer_IPA.png"],
  ["lager", "Lager", "alcohol", 500, 12, 700, "legal", {"hydration":-2,"stress":-5}, ["lager beer"], "beer.png"],
  ["red_wine", "Red Wine", "alcohol", 750, 12, 1800, "legal", {"hydration":-3,"stress":-8}, ["red wine bottle"], null],
  ["white_wine", "White Wine", "alcohol", 750, 12, 1800, "legal", {"hydration":-3,"stress":-8}, ["white wine bottle"], "wine.png"],
  ["whiskey", "Whiskey", "alcohol", 700, 12, 3200, "legal", {"hydration":-5,"stress":-10}, ["whiskey bottle"], null],
  ["vodka", "Vodka", "alcohol", 700, 12, 2800, "legal", {"hydration":-5,"stress":-10}, ["vodka bottle"], "absolute_vodka.png"],
  ["rum", "Rum", "alcohol", 700, 12, 2600, "legal", {"hydration":-5,"stress":-9}, ["rum bottle"], null],
  ["champagne", "Champagne", "alcohol", 750, 12, 4200, "legal", {"hydration":-3,"stress":-7}, ["champagne bottle"], null],
]);
