import { defineCategory } from './catalog-helpers.js';

export const FOOD_ITEMS = defineCategory("food", [
  ["sandwich", "Sandwich", "prepared", 350, 10, 1200, "legal", {"satiety":15}, ["sandwich"], null],
  ["ham_sandwich", "Ham Sandwich", "prepared", 360, 10, 1400, "legal", {"satiety":18}, ["ham sandwich"], null],
  ["chicken_sandwich", "Chicken Sandwich", "prepared", 380, 10, 1600, "legal", {"satiety":20}, ["chicken sandwich"], null],
  ["cheese_sandwich", "Cheese Sandwich", "prepared", 340, 10, 1300, "legal", {"satiety":17}, ["cheese sandwich"], null],
  ["burger", "Burger", "prepared", 420, 10, 1800, "legal", {"satiety":24}, ["burger"], null],
  ["double_burger", "Double Burger", "prepared", 560, 10, 2600, "legal", {"satiety":32}, ["double burger"], null],
  ["cheeseburger", "Cheeseburger", "prepared", 450, 10, 2000, "legal", {"satiety":26}, ["cheeseburger"], null],
  ["chicken_burger", "Chicken Burger", "prepared", 430, 10, 1900, "legal", {"satiety":25}, ["chicken burger"], null],
  ["hotdog", "Hot Dog", "prepared", 310, 10, 1200, "legal", {"satiety":16}, ["hot dog"], null],
  ["pizza_slice", "Pizza Slice", "prepared", 220, 10, 700, "legal", {"satiety":12}, ["pizza slice"], null],
  ["pepperoni_slice", "Pepperoni Pizza Slice", "prepared", 240, 10, 800, "legal", {"satiety":13}, ["pepperoni pizza slice"], null],
  ["margherita_slice", "Margherita Pizza Slice", "prepared", 230, 10, 750, "legal", {"satiety":12}, ["margherita pizza slice"], null],
  ["taco", "Taco", "prepared", 220, 10, 900, "legal", {"satiety":13}, ["taco"], null],
  ["burrito", "Burrito", "prepared", 480, 10, 1800, "legal", {"satiety":25}, ["burrito"], null],
  ["fried_chicken", "Fried Chicken", "prepared", 390, 10, 1700, "legal", {"satiety":23}, ["fried chicken"], null],
  ["fries", "French Fries", "prepared", 260, 10, 600, "legal", {"satiety":10}, ["french fries"], null],
  ["salad", "Garden Salad", "prepared", 320, 10, 1100, "legal", {"satiety":15}, ["garden salad"], null],
  ["caesar_salad", "Caesar Salad", "prepared", 360, 10, 1500, "legal", {"satiety":19}, ["caesar salad"], null],
  ["pasta_box", "Pasta Box", "prepared", 480, 10, 1700, "legal", {"satiety":24}, ["pasta box"], null],
  ["rice_bowl", "Rice Bowl", "prepared", 450, 10, 1500, "legal", {"satiety":22}, ["rice bowl"], null],
  ["steak_plate", "Steak Plate", "prepared", 650, 10, 4200, "legal", {"satiety":38}, ["steak plate"], null],
  ["fish_plate", "Grilled Fish Plate", "prepared", 580, 10, 3600, "legal", {"satiety":34}, ["grilled fish plate"], null],
  ["donut", "Donut", "snack", 120, 20, 350, "legal", {"satiety":6}, ["donut"], null],
  ["chocolate_donut", "Chocolate Donut", "snack", 130, 20, 400, "legal", {"satiety":7}, ["chocolate donut"], null],
  ["muffin", "Muffin", "snack", 140, 20, 450, "legal", {"satiety":7}, ["muffin"], null],
  ["croissant", "Croissant", "snack", 110, 20, 400, "legal", {"satiety":6}, ["croissant"], null],
  ["cookie", "Cookie", "snack", 70, 20, 250, "legal", {"satiety":4}, ["cookie"], null],
  ["chocolate_bar", "Chocolate Bar", "snack", 100, 20, 300, "legal", {"satiety":5}, ["chocolate bar"], null],
  ["chips", "Potato Chips", "snack", 120, 20, 350, "legal", {"satiety":5}, ["potato chips"], null],
  ["protein_bar", "Protein Bar", "snack", 85, 20, 500, "legal", {"satiety":8}, ["protein bar"], null],
  ["apple", "Apple", "produce", 180, 20, 250, "legal", {"satiety":5}, ["apple"], null],
  ["banana", "Banana", "produce", 160, 20, 220, "legal", {"satiety":5}, ["banana"], null],
  ["orange", "Orange", "produce", 190, 20, 250, "legal", {"satiety":5}, ["orange"], null],
  ["strawberries", "Strawberries", "produce", 250, 20, 500, "legal", {"satiety":7}, ["strawberries"], null],
  ["bread_loaf", "Bread Loaf", "ingredient", 500, 20, 450, "legal", {"satiety":8}, ["bread loaf"], null],
  ["raw_chicken", "Raw Chicken", "ingredient", 650, 20, 900, "legal", {}, ["raw chicken"], null],
  ["raw_beef", "Raw Beef", "ingredient", 700, 20, 1200, "legal", {}, ["raw beef"], null],
  ["cheese_block", "Cheese Block", "ingredient", 400, 20, 900, "legal", {}, ["cheese block"], null],
  ["egg_carton", "Egg Carton", "ingredient", 650, 20, 650, "legal", {}, ["egg carton"], null],
  ["rice_bag", "Rice Bag", "ingredient", 1000, 20, 700, "legal", {}, ["rice bag"], null],
]);
