import { ItemDefinitionSchema, type ItemDefinition, type ItemLegality } from '@sol-dorado/contracts/items';

type ImportedWeaponRow = readonly [string,string,string,number,number,ItemLegality,string,string,string,string,string,string|null,string|null,number|null,number|null,string];
const PACK_URL = 'https://quaternius.com/packs/ultimategun.html';
const RAINMAD_URL = 'https://items.rainmad.com/';
const UPLOADED_ARCHIVE_SHA256 = '3bb519fbbf795915eaf5b9ecbf31b22afb2bc3d5712f1b29cb045ddcd0a2bc2f';
const DISCLAIMER = 'Representative real-world reference only; the generic Quaternius mesh is not asserted to be an exact replica.';

/** The uploaded set contains 40 generic firearm FBX assets and 15 generic accessory FBX assets. */
const rows: readonly ImportedWeaponRow[] = [
  ["qu_pistol_01","Service 9mm Pistol","firearm_pistol",720,52000,"regulated","FBX/Pistol_1.fbx","weapon_pistol.png","Glock 17 Gen5","Glock","full-size semi-automatic pistol","9×19 mm","semi-automatic",17,630,"https://en.wikipedia.org/wiki/Glock"],
  ["qu_pistol_02","Duty DA/SA Pistol","firearm_pistol",960,68000,"regulated","FBX/Pistol_2.fbx","weapon_pistol.png","SIG Sauer P226","SIG Sauer","full-size DA/SA pistol","9×19 mm","semi-automatic",15,964,"https://en.wikipedia.org/wiki/SIG_Sauer_P226"],
  ["qu_pistol_03","Full-Size 92-Type Pistol","firearm_pistol",950,62000,"regulated","FBX/Pistol_3.fbx","weapon_pistol.png","Beretta 92FS","Beretta","full-size service pistol","9×19 mm","semi-automatic",15,945,"https://en.wikipedia.org/wiki/Beretta_92"],
  ["qu_pistol_04","Steel-Frame 75-Type Pistol","firearm_pistol",1000,59000,"regulated","FBX/Pistol_4.fbx","weapon_pistol.png","CZ 75 B","Česká zbrojovka","steel-frame service pistol","9×19 mm","semi-automatic",16,1000,"https://en.wikipedia.org/wiki/CZ_75"],
  ["qu_pistol_05","Classic .45 Pistol","firearm_pistol",1100,72000,"regulated","FBX/Pistol_5.fbx","weapon_snspistol.png","M1911A1","Multiple manufacturers","single-stack service pistol",".45 ACP","semi-automatic",7,1100,"https://en.wikipedia.org/wiki/M1911_pistol"],
  ["qu_pistol_06","Large-Frame Magnum Pistol","firearm_pistol",1990,165000,"regulated","FBX/Pistol_6.fbx","weapon_snspistol.png","Desert Eagle Mark XIX","Magnum Research","large-frame gas-operated pistol",".50 AE","semi-automatic",7,1998,"https://en.wikipedia.org/wiki/Desert_Eagle"],
  ["qu_revolver_01","Medium-Frame .357 Revolver","firearm_revolver",1200,82000,"regulated","FBX/Revolver_1.fbx","weapon_revolver.png","Colt Python","Colt","double-action revolver",".357 Magnum","double-action",6,1200,"https://en.wikipedia.org/wiki/Colt_Python"],
  ["qu_revolver_02","Service .357 Revolver","firearm_revolver",1050,69000,"regulated","FBX/Revolver_2.fbx","weapon_revolver.png","Smith & Wesson Model 19","Smith & Wesson","double-action revolver",".357 Magnum","double-action",6,1075,"https://en.wikipedia.org/wiki/Smith_%26_Wesson_Model_19"],
  ["qu_revolver_03","Large-Frame .44 Revolver","firearm_revolver",1400,96000,"regulated","FBX/Revolver_3.fbx","weapon_revolver.png","Smith & Wesson Model 29","Smith & Wesson","large-frame revolver",".44 Magnum","double-action",6,1400,"https://en.wikipedia.org/wiki/Smith_%26_Wesson_Model_29"],
  ["qu_revolver_04","Heavy-Duty .357 Revolver","firearm_revolver",1250,76000,"regulated","FBX/Revolver_4.fbx","weapon_revolver.png","Ruger GP100","Sturm, Ruger & Co.","double-action revolver",".357 Magnum","double-action",6,1270,"https://en.wikipedia.org/wiki/Ruger_GP100"],
  ["qu_revolver_05","Low-Bore-Axis Revolver","firearm_revolver",900,98000,"regulated","FBX/Revolver_5.fbx","weapon_revolver.png","Chiappa Rhino 60DS","Chiappa Firearms","low-bore-axis revolver",".357 Magnum","double-action",6,936,"https://en.wikipedia.org/wiki/Chiappa_Rhino"],
  ["qu_smg_01","Roller-Delayed 9mm SMG","firearm_smg",2900,148000,"regulated","FBX/SubmachineGun_1.fbx","weapon_smg.png","Heckler & Koch MP5A3","Heckler & Koch","submachine gun","9×19 mm","select-fire",30,2880,"https://en.wikipedia.org/wiki/Heckler_%26_Koch_MP5"],
  ["qu_smg_02","Open-Bolt 9mm SMG","firearm_smg",3500,132000,"regulated","FBX/SubmachineGun_2.fbx","weapon_smg.png","Uzi","Israel Military Industries","submachine gun","9×19 mm","select-fire",32,3500,"https://en.wikipedia.org/wiki/Uzi"],
  ["qu_smg_03","Compact .45 SMG","firearm_smg",2850,118000,"regulated","FBX/SubmachineGun_3.fbx","weapon_machinepistol.png","MAC-10","Military Armament Corporation","compact submachine gun",".45 ACP","select-fire",30,2840,"https://en.wikipedia.org/wiki/MAC-10"],
  ["qu_smg_04","Personal-Defense SMG","firearm_smg",1900,185000,"regulated","FBX/SubmachineGun_4.fbx","weapon_compactrifle.png","Heckler & Koch MP7A1","Heckler & Koch","personal defence weapon","4.6×30 mm","select-fire",40,1900,"https://en.wikipedia.org/wiki/Heckler_%26_Koch_MP7"],
  ["qu_smg_05","Vector-Style SMG","firearm_smg",2700,178000,"regulated","FBX/SubmachineGun_5.fbx","weapon_compactrifle.png","KRISS Vector","KRISS USA","delayed-blowback submachine gun",".45 ACP","select-fire",25,2700,"https://en.wikipedia.org/wiki/KRISS_Vector"],
  ["qu_assault_rifle_01","7.62 Service Rifle","firearm_rifle",3300,172000,"regulated","FBX/AssaultRifle_1.fbx","weapon_assaultrifle.png","AKM","Kalashnikov Concern / historical Soviet production","assault rifle","7.62×39 mm","select-fire",30,3300,"https://en.wikipedia.org/wiki/AKM"],
  ["qu_assault_rifle_02","5.56 Full-Length Service Rifle","firearm_rifle",3400,185000,"regulated","FBX/AssaultRifle_2.fbx","weapon_assaultrifle.png","M16A4","Colt / FN and others","assault rifle","5.56×45 mm NATO","select-fire",30,3400,"https://en.wikipedia.org/wiki/M16_rifle"],
  ["qu_assault_rifle_03","5.56 Carbine","firearm_rifle",3000,195000,"regulated","FBX/AssaultRifle_3.fbx","weapon_carbinerifle.png","M4A1","Colt / FN and others","carbine","5.56×45 mm NATO","select-fire",30,3000,"https://en.wikipedia.org/wiki/M4_carbine"],
  ["qu_assault_rifle_04","Compact 5.56 Rifle","firearm_rifle",2820,205000,"regulated","FBX/AssaultRifle_4.fbx","weapon_carbinerifle.png","Heckler & Koch G36C","Heckler & Koch","compact assault rifle","5.56×45 mm NATO","select-fire",30,2820,"https://en.wikipedia.org/wiki/Heckler_%26_Koch_G36"],
  ["qu_assault_rifle_05","Swiss 5.56 Service Rifle","firearm_rifle",4100,218000,"regulated","FBX/AssaultRifle_5.fbx","weapon_assaultrifle.png","SIG SG 550","SIG Sauer / Swiss Arms","assault rifle","5.56×45 mm NATO","select-fire",20,4100,"https://en.wikipedia.org/wiki/SIG_SG_550"],
  ["qu_battle_rifle_01","Modular 5.56 Rifle","firearm_battle_rifle",3200,225000,"regulated","FBX/AssaultRifle2_1.fbx","weapon_carbinerifle.png","FN SCAR-L","FN Herstal","modular assault rifle","5.56×45 mm NATO","select-fire",30,3200,"https://en.wikipedia.org/wiki/FN_SCAR"],
  ["qu_battle_rifle_02","7.62 Battle Rifle","firearm_battle_rifle",4300,205000,"regulated","FBX/AssaultRifle2_2.fbx","weapon_marksmanrifle.png","FN FAL","FN Herstal","battle rifle","7.62×51 mm NATO","select-fire",20,4300,"https://en.wikipedia.org/wiki/FN_FAL"],
  ["qu_battle_rifle_03","Roller-Delayed 7.62 Rifle","firearm_battle_rifle",4400,198000,"regulated","FBX/AssaultRifle2_3.fbx","weapon_marksmanrifle.png","Heckler & Koch G3A3","Heckler & Koch","battle rifle","7.62×51 mm NATO","select-fire",20,4400,"https://en.wikipedia.org/wiki/Heckler_%26_Koch_G3"],
  ["qu_battle_rifle_04","Traditional 7.62 Service Rifle","firearm_battle_rifle",4100,190000,"regulated","FBX/AssaultRifle2_4.fbx","weapon_marksmanrifle.png","M14","Springfield Armory / U.S. service production","battle rifle","7.62×51 mm NATO","select-fire",20,4100,"https://en.wikipedia.org/wiki/M14_rifle"],
  ["qu_bullpup_01","Bullpup 5.56 Rifle","firearm_bullpup",3600,215000,"regulated","FBX/Bullpup_1.fbx","weapon_assaultrifle.png","Steyr AUG A1","Steyr Arms","bullpup assault rifle","5.56×45 mm NATO","select-fire",30,3600,"https://en.wikipedia.org/wiki/Steyr_AUG"],
  ["qu_bullpup_02","French Bullpup Rifle","firearm_bullpup",3700,208000,"regulated","FBX/Bullpup_2.fbx","weapon_assaultrifle.png","FAMAS F1","MAS / Nexter heritage","bullpup assault rifle","5.56×45 mm NATO","select-fire",25,3700,"https://en.wikipedia.org/wiki/FAMAS"],
  ["qu_bullpup_03","Compact Bullpup Carbine","firearm_bullpup",3300,228000,"regulated","FBX/Bullpup_3.fbx","weapon_carbinerifle.png","IWI Tavor X95","Israel Weapon Industries","bullpup carbine","5.56×45 mm NATO","select-fire",30,3300,"https://en.wikipedia.org/wiki/IWI_Tavor_X95"],
  ["qu_sniper_rifle_01","Bolt-Action Precision Rifle","firearm_precision_rifle",4000,175000,"regulated","FBX/SniperRifle_1.fbx","weapon_marksmanrifle.png","Remington Model 700","Remington Arms","bolt-action precision rifle",".308 Winchester","bolt-action",5,4000,"https://en.wikipedia.org/wiki/Remington_Model_700"],
  ["qu_sniper_rifle_02","Military Precision Rifle","firearm_precision_rifle",5400,245000,"regulated","FBX/SniperRifle_2.fbx","weapon_marksmanrifle.png","M24 Sniper Weapon System","Remington Arms","bolt-action sniper rifle","7.62×51 mm NATO","bolt-action",5,5400,"https://en.wikipedia.org/wiki/M24_Sniper_Weapon_System"],
  ["qu_sniper_rifle_03","Arctic-Warfare Precision Rifle","firearm_precision_rifle",6500,285000,"regulated","FBX/SniperRifle_3.fbx","weapon_marksmanrifle.png","Accuracy International Arctic Warfare","Accuracy International","bolt-action sniper rifle",".308 Winchester","bolt-action",10,6500,"https://en.wikipedia.org/wiki/Accuracy_International_Arctic_Warfare"],
  ["qu_sniper_rifle_04","Anti-Materiel Rifle","firearm_precision_rifle",13600,420000,"regulated","FBX/SniperRifle_4.fbx","weapon_marksmanrifle.png","Barrett M82A1","Barrett Firearms Manufacturing","semi-automatic anti-materiel rifle",".50 BMG","semi-automatic",10,13600,"https://en.wikipedia.org/wiki/Barrett_M82"],
  ["qu_sniper_rifle_05","Designated Marksman Rifle","firearm_precision_rifle",4300,235000,"regulated","FBX/SniperRifle_5.fbx","weapon_marksmanrifle.png","SVD Dragunov","Kalashnikov Concern / historical Soviet production","semi-automatic designated marksman rifle","7.62×54 mmR","semi-automatic",10,4300,"https://en.wikipedia.org/wiki/Dragunov_sniper_rifle"],
  ["qu_sniper_rifle_06","Long-Range Precision Rifle","firearm_precision_rifle",12000,390000,"regulated","FBX/SniperRifle_6.fbx","weapon_marksmanrifle.png","CheyTac M200 Intervention","CheyTac USA","bolt-action long-range rifle",".408 CheyTac","bolt-action",7,12000,"https://en.wikipedia.org/wiki/CheyTac_Intervention"],
  ["qu_shotgun_01","Pump-Action 12 Gauge","firearm_shotgun",3200,98000,"regulated","FBX/Shotgun_1.fbx","weapon_pumpshotgun.png","Remington Model 870","Remington Arms","pump-action shotgun","12 gauge","pump-action",6,3200,"https://en.wikipedia.org/wiki/Remington_Model_870"],
  ["qu_shotgun_02","Utility Pump Shotgun","firearm_shotgun",3300,92000,"regulated","FBX/Shotgun_2.fbx","weapon_pumpshotgun.png","Mossberg 500","O.F. Mossberg & Sons","pump-action shotgun","12 gauge","pump-action",6,3300,"https://en.wikipedia.org/wiki/Mossberg_500"],
  ["qu_shotgun_03","Semi-Automatic Tactical Shotgun","firearm_shotgun",3820,165000,"regulated","FBX/Shotgun_3.fbx","weapon_pumpshotgun.png","Benelli M4","Benelli Armi","semi-automatic shotgun","12 gauge","semi-automatic",7,3820,"https://en.wikipedia.org/wiki/Benelli_M4"],
  ["qu_shotgun_04","Classic Pump Shotgun","firearm_shotgun",3600,115000,"regulated","FBX/Shotgun_4.fbx","weapon_pumpshotgun.png","Winchester Model 1897","Winchester Repeating Arms","pump-action shotgun","12 gauge","pump-action",5,3600,"https://en.wikipedia.org/wiki/Winchester_Model_1897"],
  ["qu_shotgun_sawed_off","Cut-Down 12 Gauge Shotgun","firearm_shotgun",2600,125000,"illegal","FBX/Shotgun_SawedOff.fbx","weapon_pumpshotgun.png","Cut-down 12-gauge shotgun","Various","shortened shotgun","12 gauge","break-action / pump-action varies",null,2600,"https://en.wikipedia.org/wiki/Sawed-off_shotgun"],
  ["qu_shotgun_short_stock","Compact 12 Gauge Shotgun","firearm_shotgun",2750,112000,"regulated","FBX/Shotgun_ShortStock.fbx","weapon_pumpshotgun.png","Mossberg 590 Shockwave","O.F. Mossberg & Sons","compact pump-action firearm","12 gauge","pump-action",6,2380,"https://en.wikipedia.org/wiki/Mossberg_500"],
  ["qu_bayonet_01","Rifle Bayonet","weapon_accessory",450,8500,"restricted","FBX/Accessories/Bayonet.fbx","weapon_knife.png","M9 bayonet","Phrobis / multiple U.S. contractors","bayonet",null,null,null,400,"https://en.wikipedia.org/wiki/M9_bayonet"],
  ["qu_bayonet_02","Modern Rifle Bayonet","weapon_accessory",500,9800,"restricted","FBX/Accessories/Bayonet_2.fbx","weapon_knife.png","OKC-3S bayonet","Ontario Knife Company","bayonet",null,null,null,510,"https://en.wikipedia.org/wiki/OKC-3S_bayonet"],
  ["qu_bipod","Rifle Bipod","weapon_accessory",400,12000,"legal","FBX/Accessories/Bipod.fbx","weapon_marksmanrifle.png","Harris S-BRM bipod","Harris Engineering","rifle support",null,null,null,380,"https://www.harrisbipods.com/"],
  ["qu_weapon_flashlight","Weapon-Mounted Flashlight","weapon_accessory",130,18000,"legal","FBX/Accessories/Flashlight.fbx","weapon_flashlight.png","SureFire X300 Ultra","SureFire","weapon light",null,null,null,125,"https://www.surefire.com/x300u-a/"],
  ["qu_foregrip","Angled Foregrip","weapon_accessory",90,6500,"legal","FBX/Accessories/Grip.fbx","weapon_carbinerifle.png","Magpul AFG-2","Magpul","foregrip",null,null,null,74,"https://magpul.com/afg-2-angled-fore-grip.html"],
  ["qu_scope_01","Reflex Optic","weapon_accessory",270,42000,"legal","FBX/Accessories/Scope_1.fbx","weapon_marksmanrifle.png","Aimpoint CompM4","Aimpoint","red-dot sight",null,null,null,335,"https://en.wikipedia.org/wiki/Aimpoint_CompM4"],
  ["qu_scope_02","Fixed-Power Combat Optic","weapon_accessory",300,68000,"legal","FBX/Accessories/Scope_2.fbx","weapon_marksmanrifle.png","Trijicon ACOG TA31","Trijicon","fixed-power optical sight",null,null,null,280,"https://en.wikipedia.org/wiki/Advanced_Combat_Optical_Gunsight"],
  ["qu_scope_03","Variable Precision Scope","weapon_accessory",850,92000,"legal","FBX/Accessories/Scope_3.fbx","weapon_marksmanrifle.png","Leupold Mark 5HD","Leupold & Stevens","variable-power rifle scope",null,null,null,850,"https://www.leupold.com/mark-5hd"],
  ["qu_suppressor_01","5.56 Suppressor","weapon_accessory",480,78000,"regulated","FBX/Accessories/Silencer_1.fbx","weapon_carbinerifle.png","SureFire SOCOM556-RC2","SureFire","sound suppressor",null,null,null,480,"https://www.surefire.com/socom556-rc2/"],
  ["qu_suppressor_02","7.62 Suppressor","weapon_accessory",510,82000,"regulated","FBX/Accessories/Silencer_2.fbx","weapon_marksmanrifle.png","Dead Air Sandman-S","Dead Air Silencers","sound suppressor",null,null,null,499,"https://deadairsilencers.com/silencers/sandman-s/"],
  ["qu_suppressor_03","Multi-Caliber Suppressor","weapon_accessory",410,88000,"regulated","FBX/Accessories/Silencer_3.fbx","weapon_marksmanrifle.png","SilencerCo Omega 300","SilencerCo","sound suppressor",null,null,null,410,"https://silencerco.com/silencers/omega-300/"],
  ["qu_suppressor_long","Long Rifle Suppressor","weapon_accessory",560,94000,"regulated","FBX/Accessories/Silencer_long.fbx","weapon_marksmanrifle.png","SureFire SOCOM762-RC2","SureFire","sound suppressor",null,null,null,560,"https://www.surefire.com/socom762-rc2/"],
  ["qu_suppressor_short","Compact Suppressor","weapon_accessory",220,76000,"regulated","FBX/Accessories/Silencer_Short.fbx","weapon_machinepistol.png","SilencerCo Omega 9K","SilencerCo","compact sound suppressor",null,null,null,220,"https://silencerco.com/silencers/omega-k-series/"],
  ["qu_stock","Adjustable Rifle Stock","weapon_accessory",250,9500,"legal","FBX/Accessories/Stock.fbx","weapon_carbinerifle.png","Magpul CTR","Magpul","adjustable rifle stock",null,null,null,250,"https://magpul.com/ctr-carbine-stock-mil-spec.html"],
  ["qu_tripod","Precision Rifle Tripod","weapon_accessory",3500,36000,"legal","FBX/Accessories/Tripod.fbx","weapon_marksmanrifle.png","BOG DeathGrip tripod","BOG","shooting tripod",null,null,null,3500,"https://www.boghunt.com/"]
];

export const QUATERNIUS_WEAPON_ITEMS: ItemDefinition[] = rows.map(([key,displayName,subcategory,unitWeightGrams,basePriceCents,legality,sourceEntry,preferredSourceFile,referenceName,manufacturer,referenceClass,cartridge,action,typicalCapacity,approximateUnloadedWeightGrams,referenceUrl]) => ItemDefinitionSchema.parse({
  key, displayName, category: 'weapon', subcategory, unitWeightGrams, stackable: false, maxStack: 1, basePriceCents, legality, useEffects: {},
  tags: ['weapon', subcategory, 'quaternius', 'imported_asset'],
  image: { provider: 'rainmad', galleryUrl: RAINMAD_URL, localPath: `/assets/items/${key}.png`, searchTerms: [displayName.toLowerCase(),referenceName.toLowerCase(),referenceClass.toLowerCase(),'quaternius'], preferredSourceFile },
  realWorldReference: { matchType: 'representative', referenceName, manufacturer, referenceClass, cartridge, action, typicalCapacity, approximateUnloadedWeightGrams, referenceUrl, disclaimer: DISCLAIMER },
  worldAssetSource: { provider: 'quaternius', pack: 'Ultimate Guns Pack', sourceEntry, uploadedArchiveSha256: UPLOADED_ARCHIVE_SHA256, sourceUrl: PACK_URL, license: 'CC0-1.0', runtimeStatus: 'source-fbx' }
}));
