import { defineCategory } from './catalog-helpers.js';

export const TOOL_ITEMS = defineCategory("tool", [
  ["toolbox", "Toolbox", "general", 5200, 1, 8500, "legal", {}, ["toolbox"], null],
  ["hammer", "Hammer", "hand_tool", 900, 1, 1800, "legal", {}, ["hammer"], null],
  ["rubber_mallet", "Rubber Mallet", "hand_tool", 700, 1, 1600, "legal", {}, ["rubber mallet"], null],
  ["screwdriver_set", "Screwdriver Set", "hand_tool", 650, 1, 2400, "legal", {}, ["screwdriver set"], null],
  ["wrench", "Adjustable Wrench", "hand_tool", 850, 1, 2200, "legal", {}, ["adjustable wrench"], null],
  ["socket_set", "Socket Set", "hand_tool", 2600, 1, 5800, "legal", {}, ["socket set"], null],
  ["pliers", "Pliers", "hand_tool", 420, 1, 1700, "legal", {}, ["pliers"], null],
  ["wire_cutters", "Wire Cutters", "hand_tool", 380, 1, 1900, "legal", {}, ["wire cutters"], null],
  ["crowbar", "Crowbar", "hand_tool", 2200, 1, 3200, "legal", {}, ["crowbar"], null],
  ["bolt_cutters", "Bolt Cutters", "hand_tool", 3800, 1, 6200, "legal", {}, ["bolt cutters"], null],
  ["handsaw", "Hand Saw", "hand_tool", 900, 1, 2600, "legal", {}, ["hand saw"], null],
  ["hacksaw", "Hacksaw", "hand_tool", 650, 1, 2400, "legal", {}, ["hacksaw"], null],
  ["drill", "Cordless Drill", "power_tool", 2100, 1, 7600, "legal", {}, ["cordless drill"], null],
  ["impact_driver", "Impact Driver", "power_tool", 1900, 1, 8200, "legal", {}, ["impact driver"], null],
  ["angle_grinder", "Angle Grinder", "power_tool", 2600, 1, 8900, "legal", {}, ["angle grinder"], null],
  ["soldering_iron", "Soldering Iron", "electronics_tool", 450, 1, 3200, "legal", {}, ["soldering iron"], null],
  ["multimeter", "Multimeter", "electronics_tool", 550, 1, 4800, "legal", {}, ["multimeter"], null],
  ["flashlight", "Flashlight", "utility", 400, 1, 1800, "legal", {}, ["flashlight"], null],
  ["headlamp", "Headlamp", "utility", 180, 1, 2200, "legal", {}, ["headlamp"], null],
  ["shovel", "Shovel", "work_tool", 2100, 1, 3000, "legal", {}, ["shovel"], null],
  ["pickaxe", "Pickaxe", "work_tool", 3000, 1, 4200, "legal", {}, ["pickaxe"], null],
  ["axe", "Axe", "work_tool", 2500, 1, 3800, "legal", {}, ["axe"], null],
  ["fishing_rod", "Fishing Rod", "outdoor", 1200, 1, 4500, "legal", {}, ["fishing rod"], null],
  ["lockpick_set", "Lockpick Set", "security", 160, 5, 3200, "restricted", {}, ["lockpick set"], null],
  ["repair_kit", "Repair Kit", "repair", 4200, 5, 6800, "legal", {}, ["repair kit"], null],
]);
