import { useEffect, useMemo, useState } from 'react';
import type { Business, BusinessesState } from '@sol-dorado/contracts/businesses';
import { addStaff, claimBusiness, getBusinesses, orderStock, payTaxes, posSale, renewLicense, runPayroll, setBusinessOpen, setHours, setPrice } from './businesses-api';
import { useI18n } from '../../i18n';

const money=(cents:number)=>new Intl.NumberFormat(undefined,{style:'currency',currency:'USD'}).format(cents/100);
const daysBg=['Нед','Пон','Вт','Ср','Чет','Пет','Съб']; const daysEn=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];

export function BusinessesView(){
  const { locale }=useI18n(); const bg=locale==='bg';
  const [state,setState]=useState<BusinessesState|null>(null); const [selectedId,setSelectedId]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [notice,setNotice]=useState<string|null>(null);
  useEffect(()=>{getBusinesses().then(s=>{setState(s);setSelectedId(id=>id??s.businesses[0]?.id??null);}).catch(e=>setError(e instanceof Error?e.message:String(e)));},[]);
  const business=useMemo(()=>state?.businesses.find(b=>b.id===selectedId)??state?.businesses[0]??null,[state,selectedId]);
  async function act(task:()=>Promise<BusinessesState>,message:string){setBusy(true);setError(null);setNotice(null);try{setState(await task());setNotice(message);}catch(e){setError(localizeError(e instanceof Error?e.message:String(e),bg));}finally{setBusy(false);}}
  if(!state)return <section className="grid min-h-[40vh] place-items-center text-sm text-slate-400">{error??(bg?'Зареждане на бизнес системата…':'Loading business system…')}</section>;
  if(!business)return <section className="rounded-2xl border border-slate-700/60 bg-slate-950/50 p-5">{bg?'Няма регистрирани бизнеси.':'No registered businesses.'}</section>;
  const operating=business.accounts.find(a=>a.accountKey==='operating')?.balanceCents??0;
  return <section className="mx-auto flex w-full max-w-[1500px] flex-col gap-4 pb-8">
    <header className="rounded-2xl border border-amber-300/15 bg-[linear-gradient(135deg,rgba(25,21,13,.96),rgba(8,17,22,.96))] p-4 shadow-xl">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.22em] text-amber-300">SOL DORADO COMMERCE</div><h1 className="mt-1 text-xl font-black text-slate-50">{bg?'Бизнеси · компании · търговия':'Businesses · companies · commerce'}</h1><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-400">{bg?'Една оперативна система свързва имот, персонал, фирмени средства, наличности, доставчици, POS, лицензи, данъци и репутация. Имотът и бизнесът остават отделни активи.':'One operating system connects property, staff, company funds, stock, suppliers, POS, licenses, taxes and reputation. Property and business remain separate assets.'}</p></div><div className="flex flex-wrap gap-2 text-xs"><Pill>{state.businesses.length} {bg?'регистрирани':'registered'}</Pill><Pill>{state.businesses.filter(b=>b.status==='open').length} {bg?'отворени':'open'}</Pill><Pill>{state.businesses.filter(b=>b.ownerPlayerId).length} {bg?'със собственик':'owned'}</Pill></div></div>
    </header>
    {(error||notice)&&<div className={`rounded-xl border px-4 py-3 text-sm ${error?'border-red-300/20 bg-red-400/8 text-red-100':'border-emerald-300/20 bg-emerald-400/8 text-emerald-100'}`}>{error??notice}</div>}
    <div className="grid min-h-0 gap-4 lg:grid-cols-[270px_minmax(0,1fr)]">
      <aside className="rounded-2xl border border-slate-700/60 bg-[#0b151b]/95 p-2"><div className="px-3 py-2 text-[10px] font-black uppercase tracking-[.18em] text-slate-500">{bg?'Оператори в града':'City operators'}</div>{state.businesses.map(b=><button key={b.id} onClick={()=>setSelectedId(b.id)} className={`mb-1 w-full rounded-xl border px-3 py-3 text-left transition ${b.id===business.id?'border-amber-300/35 bg-amber-300/10':'border-transparent hover:border-slate-600 hover:bg-slate-800/40'}`}><div className="flex items-center justify-between gap-2"><b className="text-sm text-slate-100">{b.name}</b><span className={`h-2 w-2 rounded-full ${b.status==='open'?'bg-emerald-400':b.status==='suspended'?'bg-red-400':'bg-slate-600'}`}/></div><div className="mt-1 text-xs text-slate-500">{kindLabel(b.kind,bg)} · {b.district}</div><div className="mt-2 text-[10px] font-bold uppercase tracking-wide text-slate-500">{b.ownerPlayerId?(b.canManage?(bg?'Твоят достъп':'Your access'):(bg?'Частен оператор':'Private operator')):(bg?'Без собственик':'Unowned')}</div></button>)}</aside>
      <main className="min-w-0 space-y-4">
        <section className="rounded-2xl border border-slate-700/60 bg-[#0b151b]/95 p-4"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-black text-white">{business.name}</h2><Status status={business.status} bg={bg}/></div><p className="mt-1 text-sm text-slate-400">{kindLabel(business.kind,bg)} · {business.streetSegment} · {business.district}</p><p className="mt-2 text-xs text-slate-500">{business.propertyName?(bg?`Оперативен адрес: ${business.propertyName}. Собствеността върху имота не е собственост върху фирмата.`:`Operating address: ${business.propertyName}. Owning the property is not owning the company.`):(bg?'Бизнесът има оперативна локация без обвързана собственост върху имот.':'The business has an operating location without linked property ownership.')}</p></div><div className="grid grid-cols-3 gap-2"><Metric label={bg?'Оперативна сметка':'Operating'} value={money(operating)}/><Metric label={bg?'Репутация':'Reputation'} value={`${business.reputation}/100`}/><Metric label={bg?'Данъци за плащане':'Taxes due'} value={money(business.dueTaxesCents)}/></div></div>
          <div className="mt-4 flex flex-wrap gap-2">{!business.ownerPlayerId&&<Action disabled={busy} onClick={()=>act(()=>claimBusiness(business.id),bg?'Бизнесът е регистриран на твое име.':'Business ownership registered.')}>{bg?'Регистрирай собственост':'Claim ownership'}</Action>}{business.canManage&&<><Action disabled={busy} onClick={()=>act(()=>setBusinessOpen(business.id,business.status!=='open'),business.status==='open'?(bg?'Обектът е затворен.':'Business closed.'):(bg?'Обектът е отворен.':'Business opened.'))}>{business.status==='open'?(bg?'Затвори обекта':'Close business'):(bg?'Отвори обекта':'Open business')}</Action>{business.dueTaxesCents>0&&<Action disabled={busy} onClick={()=>act(()=>payTaxes(business.id),bg?'Данъчните задължения са платени.':'Tax obligations paid.')}>{bg?'Плати данъци':'Pay taxes'}</Action>}<Action disabled={busy} onClick={()=>act(()=>runPayroll(business.id),bg?'Payroll е изпълнен.':'Payroll completed.')}>{bg?'Изпълни payroll':'Run payroll'}</Action></>}</div>
        </section>
        <div className="grid gap-4 xl:grid-cols-2"><StockPanel business={business} bg={bg} busy={busy} act={act}/><StaffPanel business={business} bg={bg} busy={busy} act={act}/></div>
        <div className="grid gap-4 xl:grid-cols-2"><CompliancePanel business={business} bg={bg} busy={busy} act={act}/><LedgerPanel business={business} bg={bg}/></div>
      </main>
    </div>
  </section>;
}

function StockPanel({business,bg,busy,act}:{business:Business;bg:boolean;busy:boolean;act:(t:()=>Promise<BusinessesState>,m:string)=>Promise<void>}){
 const [qty,setQty]=useState(6); const [price,setPriceValue]=useState<Record<string,string>>({}); const supplier=business.suppliers[0];
 return <Panel title={bg?'Наличности · доставчици · POS':'Stock · suppliers · POS'} subtitle={bg?'Физическа наличност и реални фирмени движения':'Physical stock and real company movements'}>{business.stock.length===0?<p className="text-sm text-slate-500">{bg?'Няма заредени артикули.':'No stock loaded.'}</p>:<div className="space-y-2">{business.stock.map(item=><div key={item.itemKey} className="rounded-xl border border-slate-700/60 bg-slate-950/30 p-3"><div className="flex items-start justify-between gap-3"><div><b className="text-sm text-slate-100">{item.displayName}</b><div className={`mt-1 text-xs ${item.quantity<=item.reorderPoint?'text-amber-300':'text-slate-500'}`}>{item.quantity} {bg?'бр.':'units'} · {bg?'праг':'reorder'} {item.reorderPoint}</div></div><b className="text-sm text-emerald-300">{item.priceCents?money(item.priceCents):'—'}</b></div>{business.canManage&&<div className="mt-3 flex flex-wrap gap-2"><input aria-label={bg?'Цена':'Price'} value={price[item.itemKey]??String((item.priceCents??0)/100)} onChange={e=>setPriceValue(v=>({...v,[item.itemKey]:e.target.value}))} className="min-h-10 w-24 rounded-lg border border-slate-700 bg-slate-900 px-2 text-sm text-white"/><button disabled={busy} onClick={()=>act(()=>setPrice(business.id,item.itemKey,Math.max(1,Math.round(Number(price[item.itemKey]??((item.priceCents??0)/100))*100))),bg?'Цената е обновена.':'Price updated.')} className="min-h-10 rounded-lg border border-slate-600 px-3 text-xs font-bold text-slate-200">{bg?'Цена':'Set price'}</button>{supplier&&<><input type="number" min="1" max="1000" value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)))} className="min-h-10 w-16 rounded-lg border border-slate-700 bg-slate-900 px-2 text-sm text-white"/><button disabled={busy} onClick={()=>act(()=>orderStock(business.id,supplier.id,item.itemKey,qty),bg?'Доставката е приета в склада.':'Supplier delivery received.')} className="min-h-10 rounded-lg border border-cyan-300/20 bg-cyan-300/8 px-3 text-xs font-bold text-cyan-100">{bg?'Поръчай':'Restock'}</button></>}<button disabled={busy||business.status!=='open'||!item.priceCents||item.quantity<1} onClick={()=>act(()=>posSale(business.id,item.itemKey,1),bg?'POS продажбата е отчетена.':'POS sale recorded.')} className="min-h-10 rounded-lg border border-emerald-300/20 bg-emerald-300/8 px-3 text-xs font-bold text-emerald-100">POS · 1</button></div>}</div>)}</div>}{supplier&&<p className="mt-3 text-xs text-slate-500">{bg?'Активен доставчик':'Active supplier'}: <b className="text-slate-300">{supplier.name}</b> · {supplier.reliability}% · ~{supplier.leadTimeMinutes} min</p>}</Panel>;
}

function StaffPanel({business,bg,busy,act}:{business:Business;bg:boolean;busy:boolean;act:(t:()=>Promise<BusinessesState>,m:string)=>Promise<void>}){
 const [name,setName]=useState('Alex Rivera'); const [role,setRole]=useState<'manager'|'employee'>('employee'); const [wage,setWage]=useState(1800); const [job,setJob]=useState('retail');
 return <Panel title={bg?'Собственик · мениджър · служители':'Owner · manager · employees'} subtitle={bg?'Ролите са към business entity, не към имота':'Roles belong to the business entity, not the property'}><div className="space-y-2">{business.members.map(m=><div key={m.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-700/60 bg-slate-950/30 px-3 py-2"><div><b className="text-sm text-slate-100">{m.displayName}</b><div className="text-xs text-slate-500">{m.role} {m.jobKey?`· ${m.jobKey}`:''}</div></div><span className="text-xs font-bold text-slate-300">{m.role==='owner'?'—':money(m.wageCents)}</span></div>)}</div>{business.canManage&&<div className="mt-3 grid grid-cols-2 gap-2"><input value={name} onChange={e=>setName(e.target.value)} className="min-h-10 rounded-lg border border-slate-700 bg-slate-900 px-3 text-sm text-white"/><select value={role} onChange={e=>setRole(e.target.value as 'manager'|'employee')} className="min-h-10 rounded-lg border border-slate-700 bg-slate-900 px-2 text-sm text-white"><option value="employee">{bg?'Служител':'Employee'}</option><option value="manager">{bg?'Мениджър':'Manager'}</option></select><input value={job} onChange={e=>setJob(e.target.value)} placeholder="job key" className="min-h-10 rounded-lg border border-slate-700 bg-slate-900 px-3 text-sm text-white"/><input type="number" value={wage} onChange={e=>setWage(Math.max(0,Number(e.target.value)))} className="min-h-10 rounded-lg border border-slate-700 bg-slate-900 px-3 text-sm text-white"/><Action disabled={busy||name.trim().length<2} onClick={()=>act(()=>addStaff(business.id,name,role,job||null,wage),bg?'Служителят е добавен.':'Staff member added.')}>{bg?'Назначи':'Hire'}</Action></div>}</Panel>;
}

function CompliancePanel({business,bg,busy,act}:{business:Business;bg:boolean;busy:boolean;act:(t:()=>Promise<BusinessesState>,m:string)=>Promise<void>}){
 const days=bg?daysBg:daysEn; return <Panel title={bg?'Работно време · лицензи · такси':'Hours · licenses · fees'} subtitle={bg?'Оперативният статус зависи от compliance':'Operating status depends on compliance'}><div className="space-y-2">{business.licenses.map(l=><div key={l.id} className="flex items-center justify-between rounded-xl border border-slate-700/60 bg-slate-950/30 px-3 py-2"><div><b className="text-sm text-slate-100">{l.name}</b><div className="text-xs text-slate-500">{l.required?(bg?'Задължителен':'Required'):(bg?'Допълнителен':'Optional')} · {money(l.feeCents)}</div></div><div className="flex items-center gap-2"><span className={`text-xs font-black uppercase ${l.status==='active'?'text-emerald-300':'text-red-300'}`}>{l.status}</span>{business.canManage&&<button disabled={busy} onClick={()=>act(()=>renewLicense(business.id,l.id),bg?'Лицензът е подновен.':'License renewed.')} className="min-h-9 rounded-lg border border-slate-600 px-2 text-xs text-slate-200">{bg?'Поднови':'Renew'}</button>}</div></div>)}</div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4 xl:grid-cols-2 2xl:grid-cols-4">{business.hours.map(h=><button key={h.dayOfWeek} disabled={!business.canManage||busy} onClick={()=>act(()=>setHours(business.id,h.dayOfWeek,h.closed?'08:00':null,h.closed?'22:00':null,!h.closed),bg?'Работното време е обновено.':'Opening hours updated.')} className="min-h-14 rounded-xl border border-slate-700 bg-slate-950/30 px-2 text-left disabled:opacity-70"><b className="text-xs text-slate-300">{days[h.dayOfWeek]}</b><div className="mt-1 text-[11px] text-slate-500">{h.closed?(bg?'Почивен':'Closed'):`${h.opensAt}–${h.closesAt}`}</div></button>)}</div></Panel>;
}
function LedgerPanel({business,bg}:{business:Business;bg:boolean}){return <Panel title={bg?'Фирмен ledger':'Business ledger'} subtitle={bg?'Продажби, доставки, payroll, данъци и лицензи':'Sales, suppliers, payroll, taxes and licenses'}>{business.ledger.length===0?<p className="text-sm text-slate-500">{bg?'Все още няма движения.':'No movements yet.'}</p>:<div className="space-y-1">{business.ledger.map(e=><div key={e.id} className="grid grid-cols-[1fr_auto] gap-3 border-b border-slate-800/80 py-2 last:border-0"><div><b className="text-xs text-slate-200">{e.memo}</b><div className="text-[10px] uppercase tracking-wide text-slate-600">{e.entryType} · {new Date(e.createdAt).toLocaleString()}</div></div><b className={`text-xs ${e.direction==='in'?'text-emerald-300':'text-amber-300'}`}>{e.direction==='in'?'+':'−'}{money(e.amountCents)}</b></div>)}</div>}</Panel>}
function Panel({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-700/60 bg-[#0b151b]/95 p-4"><h3 className="text-sm font-black text-slate-100">{title}</h3><p className="mb-3 mt-1 text-xs text-slate-500">{subtitle}</p>{children}</section>}
function Action({children,onClick,disabled}:{children:React.ReactNode;onClick:()=>void;disabled?:boolean}){return <button disabled={disabled} onClick={onClick} className="min-h-11 rounded-xl border border-amber-300/25 bg-amber-300/10 px-4 text-sm font-black text-amber-100 hover:border-amber-300/45 disabled:cursor-not-allowed disabled:opacity-40">{children}</button>}
function Pill({children}:{children:React.ReactNode}){return <span className="rounded-full border border-slate-700 bg-slate-950/40 px-3 py-1.5 font-bold text-slate-300">{children}</span>}
function Metric({label,value}:{label:string;value:string}){return <div className="min-w-[105px] rounded-xl border border-slate-700/60 bg-slate-950/40 p-3"><div className="text-[9px] font-black uppercase tracking-wider text-slate-600">{label}</div><div className="mt-1 text-sm font-black text-slate-100">{value}</div></div>}
function Status({status,bg}:{status:Business['status'];bg:boolean}){return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-wider ${status==='open'?'bg-emerald-400/10 text-emerald-300':status==='suspended'?'bg-red-400/10 text-red-300':'bg-slate-700/50 text-slate-400'}`}>{status==='open'?(bg?'отворен':'open'):status==='closed'?(bg?'затворен':'closed'):(bg?'спрян':'suspended')}</span>}
function kindLabel(kind:Business['kind'],bg:boolean){const labels:Record<Business['kind'],[string,string]>={convenience_store:['Магазин','Convenience store'],restaurant:['Ресторант','Restaurant'],mechanic_shop:['Автосервиз','Mechanic shop'],dealership:['Автокъща','Dealership'],logistics:['Логистика','Logistics'],nightclub:['Нощен клуб','Nightclub']};return labels[kind][bg?0:1];}
function localizeError(code:string,bg:boolean){const map:Record<string,[string,string]>={business_already_owned:['Бизнесът вече има собственик.','Business already has an owner.'],business_manage_forbidden:['Нямаш управленски права за този бизнес.','You do not have management access.'],business_license_block:['Задължителен лиценз блокира отварянето.','A required license blocks opening.'],business_insufficient_funds:['Недостатъчна наличност по оперативната сметка.','Insufficient operating funds.'],business_stock_insufficient:['Недостатъчна стока за тази продажба.','Insufficient stock for this sale.'],business_not_open:['Обектът трябва да е отворен за POS продажба.','The business must be open for a POS sale.'],business_payroll_empty:['Няма активен payroll за изплащане.','There is no active payroll to run.'],business_no_tax_due:['Няма данъчно задължение за плащане.','There are no taxes due.'],business_job_unknown:['Тази длъжност не съществува в canonical Jobs registry.','That job does not exist in the canonical Jobs registry.']};return map[code]?.[bg?0:1]??code;}
