import type { JobDefinition, JobSkillKey } from '@sol-dorado/contracts/jobs';

export const CAREER_XP = [0,80,190,340,540,800,1120,1510,1970,2500,3120,3840];
export const JOB_XP = [0,45,120,230,390,610,900,1260,1700,2220];
export const SKILL_XP = [0,35,95,180,300,460,670,930];

export const JOB_SKILLS: JobSkillKey[] = [
  'manual_work','logistics','driving','navigation','safety','machinery','construction','mechanical','electrical','technical',
  'customer_service','commerce','communication','leadership','agriculture','fishing','seamanship','mining','forestry','cooking','hospitality'
];

const task = (id: string, titleBg: string, titleEn: string, skill: JobSkillKey, energyCost = 4, stressDelta = 1) => ({
  id, titleBg, titleEn, skill, energyCost, stressDelta
});

export const JOBS: JobDefinition[] = [
  { id:'warehouse',icon:'📦',titleBg:'Складов помощник',titleEn:'Warehouse Helper',employerKey:'quickdrop',employerBg:'QuickDrop Logistics',employerEn:'QuickDrop Logistics',locationBg:'Cypress Freight Hub',locationEn:'Cypress Freight Hub',descriptionBg:'Приемаш, сортираш и подготвяш градски доставки.',descriptionEn:'Receive, sort and prepare city freight.',archetype:'workflow',category:'entry',requirements:[],qualification:null,gainSkills:['logistics','manual_work','machinery'],basePayCents:1700,tasks:[task('receive','Приеми входящата пратка','Receive incoming freight','logistics',3,0),task('sort','Подреди палетите безопасно','Sort pallets safely','manual_work',5,1),task('forklift','Премести палетите с техника','Move pallets with equipment','machinery',5,1),task('dispatch','Подготви експедицията','Prepare dispatch','logistics',3,1)] },
  { id:'grounds',icon:'🌿',titleBg:'Работник по поддръжка',titleEn:'Grounds Worker',employerKey:'municipal',employerBg:'Общински услуги Sol Dorado',employerEn:'Sol Dorado Municipal Services',locationBg:'Las Palmas Parks',locationEn:'Las Palmas Parks',descriptionBg:'Поддържаш паркове и обществени пространства.',descriptionEn:'Maintain parks and public spaces.',archetype:'site',category:'entry',requirements:[],qualification:null,gainSkills:['manual_work','safety','forestry'],basePayCents:1650,tasks:[task('secure','Обезопаси работната зона','Secure the work area','safety',3,0),task('green','Поддържай зелените площи','Maintain green areas','manual_work',5,0),task('trim','Окастри дървета и храсти','Trim trees and shrubs','forestry',5,1),task('inspect','Провери оборудването','Inspect equipment','safety',3,0)] },
  { id:'farmhand',icon:'🌾',titleBg:'Работник във ферма',titleEn:'Farm Hand',employerKey:'rancho',employerBg:'Rancho del Sol',employerEn:'Rancho del Sol',locationBg:'East County Farms',locationEn:'East County Farms',descriptionBg:'Грижиш се за реколта, оборудване и ежедневни задачи във фермата.',descriptionEn:'Handle crops, equipment and daily farm work.',archetype:'resource',category:'entry',requirements:[],qualification:null,gainSkills:['agriculture','manual_work','machinery'],basePayCents:1650,tasks:[task('irrigation','Провери напояването','Check irrigation','agriculture',3,0),task('harvest','Събери готовата продукция','Harvest ready produce','manual_work',5,0),task('tractor','Подготви земеделската техника','Prepare farm machinery','machinery',4,1),task('load','Подготви продукцията за транспорт','Prepare produce for transport','logistics',4,0)] },
  { id:'retail',icon:'🏪',titleBg:'Служител в магазин',titleEn:'Retail Assistant',employerKey:'mercado',employerBg:'Mercado Dorado',employerEn:'Mercado Dorado',locationBg:'Market District',locationEn:'Market District',descriptionBg:'Обслужваш клиенти, наличности и ежедневни задачи.',descriptionEn:'Handle customers, stock and daily retail work.',archetype:'customer',category:'entry',requirements:[],qualification:null,gainSkills:['customer_service','commerce','communication'],basePayCents:1600,tasks:[task('customers','Обслужи клиентите','Serve customers','customer_service',2,1),task('stock','Провери наличностите','Check stock','commerce',3,0),task('delivery','Приеми доставка','Receive stock delivery','logistics',3,0),task('floor','Подреди търговската зала','Maintain the shop floor','customer_service',2,0)] },
  { id:'delivery',icon:'📬',titleBg:'Помощник доставки',titleEn:'Delivery Assistant',employerKey:'quickdrop',employerBg:'QuickDrop Logistics',employerEn:'QuickDrop Logistics',locationBg:'Cypress Freight Hub',locationEn:'Cypress Freight Hub',descriptionBg:'Подготвяш и разнасяш градски доставки като помощник на маршрут.',descriptionEn:'Prepare and deliver local shipments as a route assistant.',archetype:'route',category:'logistics',requirements:[{skill:'logistics',level:1}],qualification:null,gainSkills:['logistics','navigation'],basePayCents:1900,tasks:[task('depot','Подготви пратките в склада','Prepare parcels at the depot','logistics',3,0),task('route','Подреди спирките по маршрут','Order the delivery stops','navigation',2,0),task('handoff','Предай пратките','Hand over parcels','customer_service',3,1),task('returns','Обработи върнатите пратки','Process returns','logistics',2,0)] },
  { id:'courier',icon:'🛵',titleBg:'Градски куриер',titleEn:'City Courier',employerKey:'dorado_express',employerBg:'Dorado Express',employerEn:'Dorado Express',locationBg:'Downtown Dispatch',locationEn:'Downtown Dispatch',descriptionBg:'Бързи пратки между бизнеси и квартали.',descriptionEn:'Run time-sensitive parcels between businesses and districts.',archetype:'route',category:'transport',requirements:[{skill:'navigation',level:1}],qualification:null,gainSkills:['navigation','driving','customer_service'],basePayCents:2000,tasks:[task('pickup','Вземи пратката','Collect the parcel','customer_service',2,0),task('plan','Избери маршрут','Plan the route','navigation',2,0),task('travel','Изпълни доставката','Complete the delivery','driving',4,1),task('proof','Потвърди предаването','Confirm handoff','communication',2,0)] },
  { id:'sanitation',icon:'🗑️',titleBg:'Служител по чистота',titleEn:'Sanitation Worker',employerKey:'waste',employerBg:'Dorado Waste Services',employerEn:'Dorado Waste Services',locationBg:'Municipal Depot',locationEn:'Municipal Depot',descriptionBg:'Работиш по маршрут за отпадъци и рискови точки.',descriptionEn:'Work a waste route and handle risky stops.',archetype:'route',category:'service',requirements:[{skill:'manual_work',level:1},{skill:'safety',level:1}],qualification:'workplace_safety',gainSkills:['manual_work','safety','logistics'],basePayCents:2200,tasks:[task('inspection','Провери защитното оборудване','Inspect protective equipment','safety',2,0),task('southside','Обслужи Southside','Service Southside','manual_work',5,1),task('cypress','Обслужи Cypress','Service Cypress','logistics',4,1),task('hazard','Обработи рискова точка','Handle a hazardous stop','safety',5,2)] },
  { id:'construction',icon:'🧱',titleBg:'Строителен работник',titleEn:'Construction Laborer',employerKey:'buildco',employerBg:'Dorado BuildCo',employerEn:'Dorado BuildCo',locationBg:'Cypress Construction Site',locationEn:'Cypress Construction Site',descriptionBg:'Физическа работа по строителни обекти.',descriptionEn:'Manual work on construction sites.',archetype:'site',category:'trades',requirements:[{skill:'manual_work',level:2},{skill:'safety',level:1}],qualification:'workplace_safety',gainSkills:['construction','safety','manual_work'],basePayCents:2400,tasks:[task('secure','Обезопаси обекта','Secure the site','safety',3,0),task('materials','Подготви материалите','Prepare materials','manual_work',5,1),task('measure','Провери размерите','Check measurements','construction',3,1),task('build','Изпълни задачата на обекта','Complete the site task','construction',6,2)] },
  { id:'kitchen',icon:'🍳',titleBg:'Помощник кухня',titleEn:'Kitchen Hand',employerKey:'elsol',employerBg:'El Sol Kitchen',employerEn:'El Sol Kitchen',locationBg:'El Camino Restaurant',locationEn:'El Camino Restaurant',descriptionBg:'Подготовка на продукти и работа по кухненски поток.',descriptionEn:'Food preparation and kitchen workflow support.',archetype:'workflow',category:'hospitality',requirements:[{skill:'manual_work',level:1}],qualification:null,gainSkills:['cooking','safety','hospitality'],basePayCents:1850,tasks:[task('prep','Подготви продуктите','Prepare ingredients','cooking',3,0),task('orders','Подреди поръчките','Prioritize orders','cooking',3,1),task('service','Подготви поръчките за сервиране','Prepare orders for service','hospitality',3,1),task('clean','Почисти станцията','Clean the station','safety',3,0)] },
  { id:'barista',icon:'☕',titleBg:'Бариста',titleEn:'Barista',employerKey:'sunset_coffee',employerBg:'Sunset Coffee',employerEn:'Sunset Coffee',locationBg:'Las Palmas Promenade',locationEn:'Las Palmas Promenade',descriptionBg:'Приготвяш напитки и управляваш натоварен клиентски поток.',descriptionEn:'Prepare drinks and manage a busy customer flow.',archetype:'service',category:'hospitality',requirements:[{skill:'cooking',level:1},{skill:'customer_service',level:1}],qualification:'food_handler',gainSkills:['cooking','customer_service','hospitality'],basePayCents:2100,tasks:[task('station','Подготви станцията','Prepare the station','safety',2,0),task('drinks','Приготви напитките','Prepare drinks','cooking',3,1),task('rush','Обслужи сутрешния поток','Handle the rush','customer_service',3,2),task('close','Затвори и отчети станцията','Close and reconcile the station','commerce',2,0)] },
  { id:'hotel_service',icon:'🛎️',titleBg:'Хотелски служител',titleEn:'Hotel Service Agent',employerKey:'mar_azul',employerBg:'Mar Azul Hotel',employerEn:'Mar Azul Hotel',locationBg:'Beachfront District',locationEn:'Beachfront District',descriptionBg:'Работиш с гости, заявки и оперативни ситуации.',descriptionEn:'Handle guests, requests and operational situations.',archetype:'service',category:'hospitality',requirements:[{skill:'customer_service',level:2}],qualification:null,gainSkills:['hospitality','communication','customer_service'],basePayCents:2300,tasks:[task('checkin','Обработи настаняванията','Handle check-ins','customer_service',2,1),task('requests','Приоритизирай заявките на гостите','Prioritize guest requests','communication',2,1),task('handover','Координирай с housekeeping','Coordinate with housekeeping','hospitality',2,0),task('incident','Реши оперативен проблем','Resolve an operational issue','communication',3,2)] },
  { id:'dock',icon:'⚓',titleBg:'Пристанищен работник',titleEn:'Dock Worker',employerKey:'port',employerBg:'Пристанище Sol Dorado',employerEn:'Port of Sol Dorado',locationBg:'South Harbor',locationEn:'South Harbor',descriptionBg:'Работиш с товар, манифести и експедиция в пристанището.',descriptionEn:'Handle cargo, manifests and loading at the port.',archetype:'workflow',category:'logistics',requirements:[{skill:'manual_work',level:2},{skill:'logistics',level:1}],qualification:'workplace_safety',gainSkills:['logistics','manual_work','safety','seamanship'],basePayCents:2500,tasks:[task('manifest','Провери манифеста','Check the manifest','logistics',2,1),task('cargo','Провери товара','Inspect cargo','safety',3,1),task('loading','Подготви товаренето','Prepare loading','manual_work',6,2),task('secure','Обезопаси товара','Secure the cargo','seamanship',4,1)] },
  { id:'mechanic_assistant',icon:'🔧',titleBg:'Помощник механик',titleEn:'Mechanic Assistant',employerKey:'atlas_auto',employerBg:'Atlas Auto Service',employerEn:'Atlas Auto Service',locationBg:'Industrial Service Row',locationEn:'Industrial Service Row',descriptionBg:'Диагностика, консумативи и базови ремонти под надзор.',descriptionEn:'Diagnostics, consumables and basic repairs under supervision.',archetype:'technical',category:'trades',requirements:[{skill:'manual_work',level:1}],qualification:null,gainSkills:['mechanical','technical','safety'],basePayCents:2300,tasks:[task('intake','Направи първичен оглед','Perform intake inspection','technical',2,0),task('service','Смени консумативите','Replace service items','mechanical',4,1),task('diagnose','Провери симптома','Diagnose the symptom','technical',3,1),task('verify','Провери ремонта','Verify the repair','safety',2,0)] },
  { id:'electrical_apprentice',icon:'⚡',titleBg:'Електротехник стажант',titleEn:'Electrical Apprentice',employerKey:'gridworks',employerBg:'GridWorks Dorado',employerEn:'GridWorks Dorado',locationBg:'Cypress Utility Yard',locationEn:'Cypress Utility Yard',descriptionBg:'Базова диагностика и поддръжка на нисковолтови системи.',descriptionEn:'Basic diagnostics and maintenance on low-voltage systems.',archetype:'technical',category:'trades',requirements:[{skill:'technical',level:1},{skill:'safety',level:1}],qualification:null,gainSkills:['electrical','technical','safety'],basePayCents:2500,tasks:[task('isolate','Изолирай работната зона','Isolate the work area','safety',2,0),task('inspect','Провери инсталацията','Inspect the installation','electrical',3,1),task('measure','Измери веригата','Measure the circuit','technical',3,1),task('repair','Изпълни базов ремонт','Perform a basic repair','electrical',4,1)] },
  { id:'delivery_driver',icon:'🚐',titleBg:'Шофьор доставки',titleEn:'Delivery Driver',employerKey:'quickdrop',employerBg:'QuickDrop Logistics',employerEn:'QuickDrop Logistics',locationBg:'Cypress Freight Hub',locationEn:'Cypress Freight Hub',descriptionBg:'Поемаш собствен маршрут, товар и отговорност за доставките.',descriptionEn:'Own a route, cargo and delivery responsibility.',archetype:'route',category:'transport',requirements:[{skill:'logistics',level:2},{skill:'navigation',level:1}],qualification:null,gainSkills:['driving','navigation','logistics'],basePayCents:2700,tasks:[task('vehicle','Провери служебния автомобил','Inspect the work vehicle','driving',2,0),task('load','Организирай товара','Organize cargo','logistics',3,0),task('route','Изпълни маршрута','Run the route','navigation',4,1),task('return','Приключи маршрута в депото','Close the route at the depot','logistics',2,0)] },
  { id:'taxi',icon:'🚕',titleBg:'Таксиметров шофьор',titleEn:'Taxi Driver',employerKey:'dorado_cab',employerBg:'Dorado Cab Co.',employerEn:'Dorado Cab Co.',locationBg:'Downtown Taxi Hub',locationEn:'Downtown Taxi Hub',descriptionBg:'Приемаш курсове, управляваш маршрут и обслужваш клиенти.',descriptionEn:'Take fares, manage routes and serve passengers.',archetype:'route',category:'transport',requirements:[{skill:'driving',level:2},{skill:'navigation',level:2},{skill:'customer_service',level:1}],qualification:'commercial_driver',gainSkills:['driving','navigation','customer_service'],basePayCents:3000,tasks:[task('pickup','Вземи клиента','Pick up the passenger','customer_service',2,1),task('route','Избери безопасен маршрут','Choose a safe route','navigation',2,0),task('drive','Изпълни курса','Complete the fare','driving',4,1),task('dropoff','Завърши курса коректно','Complete the drop-off','customer_service',2,0)] },
  { id:'fishing_deckhand',icon:'🎣',titleBg:'Моряк на риболовен кораб',titleEn:'Fishing Deckhand',employerKey:'bluewater',employerBg:'Bluewater Cooperative',employerEn:'Bluewater Cooperative',locationBg:'South Harbor Marina',locationEn:'South Harbor Marina',descriptionBg:'Работиш на палуба, с улов и морско оборудване.',descriptionEn:'Work the deck, catch and marine equipment.',archetype:'resource',category:'resource',requirements:[{skill:'manual_work',level:1}],qualification:null,gainSkills:['fishing','seamanship','safety'],basePayCents:2400,tasks:[task('gear','Подготви екипировката','Prepare the gear','seamanship',3,0),task('set','Пусни такъмите','Set the fishing gear','fishing',4,1),task('haul','Извади улова','Haul the catch','manual_work',6,1),task('sort','Сортирай и прибери улова','Sort and store the catch','fishing',3,0)] },
  { id:'mining',icon:'⛏️',titleBg:'Миньор',titleEn:'Mine Worker',employerKey:'redmesa',employerBg:'Red Mesa Mining',employerEn:'Red Mesa Mining',locationBg:'Red Mesa Quarry',locationEn:'Red Mesa Quarry',descriptionBg:'Добив, безопасност и работа с тежки материали.',descriptionEn:'Extraction, safety and heavy material handling.',archetype:'resource',category:'resource',requirements:[{skill:'manual_work',level:2},{skill:'safety',level:2}],qualification:'workplace_safety',gainSkills:['mining','machinery','safety'],basePayCents:2900,tasks:[task('check','Направи проверка на зоната','Inspect the work zone','safety',3,0),task('extract','Извърши добив','Extract material','mining',6,2),task('machine','Работи с оборудването','Operate equipment','machinery',6,2),task('load','Подготви материала за извозване','Prepare material for transport','logistics',4,1)] },
  { id:'forestry',icon:'🪵',titleBg:'Горски работник',titleEn:'Forestry Worker',employerKey:'northridge',employerBg:'North Ridge Forestry',employerEn:'North Ridge Forestry',locationBg:'North Ridge',locationEn:'North Ridge',descriptionBg:'Маркиране, поддръжка и безопасна работа в горски терен.',descriptionEn:'Marking, maintenance and safe work in forest terrain.',archetype:'resource',category:'resource',requirements:[{skill:'manual_work',level:2},{skill:'safety',level:2}],qualification:'workplace_safety',gainSkills:['forestry','safety','machinery'],basePayCents:2800,tasks:[task('survey','Огледай участъка','Survey the area','forestry',3,0),task('mark','Маркирай дърветата','Mark the trees','forestry',3,0),task('cut','Изпълни безопасна сеч','Perform controlled cutting','machinery',6,2),task('clear','Обезопаси и почисти терена','Secure and clear the terrain','safety',5,1)] }
];

export interface QualificationDefinition {
  key: string;
  titleBg: string;
  titleEn: string;
  descriptionBg: string;
  descriptionEn: string;
  careerLevel: number;
  requirements: Array<{ skill: JobSkillKey; level: number }>;
}

export const QUALIFICATIONS: QualificationDefinition[] = [
  { key:'workplace_safety',titleBg:'Безопасност на работното място',titleEn:'Workplace Safety',descriptionBg:'Базова квалификация за строителство, тежък труд и рискови обекти.',descriptionEn:'Foundation qualification for construction, heavy work and hazardous sites.',careerLevel:2,requirements:[{skill:'manual_work',level:1},{skill:'safety',level:1}] },
  { key:'food_handler',titleBg:'Безопасна работа с храни',titleEn:'Food Handler',descriptionBg:'Необходима за по-отговорни позиции с приготвяне и сервиране на храна.',descriptionEn:'Required for more responsible food preparation and service roles.',careerLevel:2,requirements:[{skill:'cooking',level:1},{skill:'safety',level:1}] },
  { key:'forklift',titleBg:'Оператор на мотокар',titleEn:'Forklift Operator',descriptionBg:'Квалификация за самостоятелна работа със складова техника.',descriptionEn:'Qualification for independent warehouse equipment operation.',careerLevel:3,requirements:[{skill:'logistics',level:2},{skill:'machinery',level:1}] },
  { key:'commercial_driver',titleBg:'Професионален водач',titleEn:'Commercial Driver',descriptionBg:'Квалификация за платени пътнически и по-отговорни транспортни задачи.',descriptionEn:'Qualification for paid passenger and higher-responsibility transport work.',careerLevel:4,requirements:[{skill:'driving',level:1},{skill:'navigation',level:2}] },
  { key:'electrical_safety',titleBg:'Електробезопасност',titleEn:'Electrical Safety',descriptionBg:'Квалификация за самостоятелни електротехнически задачи.',descriptionEn:'Qualification for independent electrical work.',careerLevel:4,requirements:[{skill:'electrical',level:2},{skill:'safety',level:2}] },
  { key:'maritime_safety',titleBg:'Морска безопасност',titleEn:'Maritime Safety',descriptionBg:'Квалификация за по-отговорна работа на пристанище и плавателни съдове.',descriptionEn:'Qualification for higher-responsibility harbor and vessel work.',careerLevel:3,requirements:[{skill:'seamanship',level:1},{skill:'safety',level:2}] },
  { key:'mechanic_basic',titleBg:'Базова механична квалификация',titleEn:'Basic Mechanical Qualification',descriptionBg:'Потвърждава базова техническа и механична компетентност.',descriptionEn:'Confirms foundational technical and mechanical competence.',careerLevel:3,requirements:[{skill:'mechanical',level:1},{skill:'technical',level:1}] }
];

export interface EventChoiceDefinition {
  id: string; labelBg: string; labelEn: string; quality: -1|0|1; payDeltaCents: number; consequenceBg: string; consequenceEn: string;
  skill?: JobSkillKey; needLevel?: number;
}
export interface EventDefinition {
  id: string; kind: 'opportunity'|'problem'|'skill'|'responsibility'; titleBg: string; titleEn: string; descriptionBg: string; descriptionEn: string;
  choices: EventChoiceDefinition[];
}

const GENERIC_EVENTS: Record<JobDefinition['archetype'], EventDefinition[]> = {
  workflow:[
    {id:'workflow_quality',kind:'skill',titleBg:'Контрол на качеството',titleEn:'Quality checkpoint',descriptionBg:'Забелязваш несъответствие преди следващата стъпка от процеса.',descriptionEn:'You spot an inconsistency before the next workflow step.',choices:[{id:'verify',labelBg:'Спри и провери',labelEn:'Stop and verify',quality:1,payDeltaCents:180,consequenceBg:'Проверката предотврати повторна работа.',consequenceEn:'The check prevented rework.',skill:'safety'},{id:'continue',labelBg:'Продължи по график',labelEn:'Keep the schedule',quality:-1,payDeltaCents:-220,consequenceBg:'Проблемът се върна по-късно и забави екипа.',consequenceEn:'The issue resurfaced and delayed the team.'}]},
    {id:'workflow_extra',kind:'responsibility',titleBg:'Колега изостава',titleEn:'A coworker is falling behind',descriptionBg:'Можеш да помогнеш, но собствената ти задача още не е приключила.',descriptionEn:'You can help, but your own work is not finished yet.',choices:[{id:'coordinate',labelBg:'Координирай задачите',labelEn:'Coordinate the work',quality:1,payDeltaCents:220,consequenceBg:'Екипът навакса без да се жертва качеството.',consequenceEn:'The team recovered without sacrificing quality.',skill:'leadership',needLevel:1},{id:'focus',labelBg:'Завърши своята задача',labelEn:'Finish your own task',quality:0,payDeltaCents:0,consequenceBg:'Запази темпото на собствената си позиция.',consequenceEn:'You kept your own station on pace.'}]}
  ],
  route:[
    {id:'route_disruption',kind:'problem',titleBg:'Маршрутът е блокиран',titleEn:'Route disruption',descriptionBg:'Инцидент затваря планираната отсечка.',descriptionEn:'An incident blocks the planned route.',choices:[{id:'reroute',labelBg:'Преизчисли маршрута',labelEn:'Re-route',quality:1,payDeltaCents:220,consequenceBg:'Избегна забавянето с добра навигация.',consequenceEn:'Good navigation avoided the delay.',skill:'navigation'},{id:'wait',labelBg:'Изчакай да отворят',labelEn:'Wait for reopening',quality:0,payDeltaCents:-80,consequenceBg:'Маршрутът продължи с малко закъснение.',consequenceEn:'The route continued with a small delay.'}]},
    {id:'route_customer',kind:'opportunity',titleBg:'Клиентът има допълнителна молба',titleEn:'Customer has an extra request',descriptionBg:'Молбата е разумна, но не е част от стандартната задача.',descriptionEn:'The request is reasonable but outside the standard task.',choices:[{id:'help',labelBg:'Помогни в разумни граници',labelEn:'Help within reason',quality:1,payDeltaCents:160,consequenceBg:'Клиентът оцени отношението.',consequenceEn:'The customer appreciated the service.',skill:'customer_service'},{id:'decline',labelBg:'Придържай се към задачата',labelEn:'Stick to the task',quality:0,payDeltaCents:0,consequenceBg:'Завърши задачата без отклонение.',consequenceEn:'You completed the task without deviation.'}]}
  ],
  customer:[
    {id:'customer_dispute',kind:'problem',titleBg:'Недоволен клиент',titleEn:'Upset customer',descriptionBg:'Клиентът твърди, че е получил грешна информация.',descriptionEn:'A customer says they were given incorrect information.',choices:[{id:'listen',labelBg:'Изслушай и провери случая',labelEn:'Listen and verify',quality:1,payDeltaCents:160,consequenceBg:'Намери решение и запази клиента.',consequenceEn:'You found a solution and retained the customer.',skill:'communication'},{id:'dismiss',labelBg:'Повтори правилото',labelEn:'Repeat the policy',quality:-1,payDeltaCents:-200,consequenceBg:'Ситуацията ескалира до управител.',consequenceEn:'The situation escalated to a manager.'}]},
    {id:'customer_queue',kind:'skill',titleBg:'Опашката расте',titleEn:'Queue building',descriptionBg:'Няколко клиента чакат едновременно.',descriptionEn:'Several customers are waiting at once.',choices:[{id:'prioritize',labelBg:'Приоритизирай бързите казуси',labelEn:'Prioritize quick cases',quality:1,payDeltaCents:120,consequenceBg:'Намали опашката без объркване.',consequenceEn:'You reduced the queue without confusion.',skill:'customer_service'},{id:'order',labelBg:'Работи по ред на пристигане',labelEn:'Work in arrival order',quality:0,payDeltaCents:0,consequenceBg:'Опашката се движи стабилно.',consequenceEn:'The queue moved steadily.'}]}
  ],
  site:[
    {id:'site_hazard',kind:'problem',titleBg:'Нова опасност на обекта',titleEn:'New site hazard',descriptionBg:'Работната зона се е променила и старото обезопасяване вече не е достатъчно.',descriptionEn:'Conditions changed and the existing safety setup is no longer enough.',choices:[{id:'secure',labelBg:'Обезопаси отново зоната',labelEn:'Secure the area again',quality:1,payDeltaCents:180,consequenceBg:'Работата продължи безопасно.',consequenceEn:'Work continued safely.',skill:'safety'},{id:'careful',labelBg:'Продължи по-внимателно',labelEn:'Proceed carefully',quality:-1,payDeltaCents:-260,consequenceBg:'Супервайзорът спря работата за корекция.',consequenceEn:'A supervisor stopped the work for correction.'}]},
    {id:'site_sequence',kind:'skill',titleBg:'Редът на задачите може да се подобри',titleEn:'Work sequence can improve',descriptionBg:'Виждаш по-ефективна последователност на следващите стъпки.',descriptionEn:'You see a more efficient sequence for the next steps.',choices:[{id:'propose',labelBg:'Предложи промяната',labelEn:'Propose the change',quality:1,payDeltaCents:180,consequenceBg:'Промяната спести време на екипа.',consequenceEn:'The change saved the team time.',skill:'leadership',needLevel:1},{id:'standard',labelBg:'Следвай плана',labelEn:'Follow the plan',quality:0,payDeltaCents:0,consequenceBg:'Работата продължи по стандартния план.',consequenceEn:'Work continued according to plan.'}]}
  ],
  service:[
    {id:'service_priority',kind:'opportunity',titleBg:'Приоритетна заявка',titleEn:'Priority request',descriptionBg:'Появява се заявка, която може да бъде решена бързо с добра координация.',descriptionEn:'A request can be resolved quickly with good coordination.',choices:[{id:'coordinate',labelBg:'Координирай решението',labelEn:'Coordinate a solution',quality:1,payDeltaCents:200,consequenceBg:'Заявката беше решена без да блокира останалата работа.',consequenceEn:'The request was resolved without blocking other work.',skill:'communication'},{id:'queue',labelBg:'Добави я към опашката',labelEn:'Add it to the queue',quality:0,payDeltaCents:0,consequenceBg:'Заявката изчака стандартния ред.',consequenceEn:'The request waited in the standard queue.'}]},
    {id:'service_mistake',kind:'problem',titleBg:'Откриваш чужда грешка',titleEn:'You spot someone else’s mistake',descriptionBg:'Можеш да я поправиш преди клиентът да я види.',descriptionEn:'You can correct it before the customer notices.',choices:[{id:'fix',labelBg:'Поправи и информирай екипа',labelEn:'Fix it and inform the team',quality:1,payDeltaCents:160,consequenceBg:'Проблемът беше отстранен и не се повтори.',consequenceEn:'The problem was corrected and did not repeat.',skill:'leadership',needLevel:1},{id:'fix_only',labelBg:'Само я поправи',labelEn:'Just fix it',quality:0,payDeltaCents:80,consequenceBg:'Клиентът не усети проблема.',consequenceEn:'The customer never saw the issue.'}]}
  ],
  technical:[
    {id:'technical_symptom',kind:'skill',titleBg:'Симптомът не съвпада с първата диагноза',titleEn:'Symptom does not match the first diagnosis',descriptionBg:'Има риск да смениш правилна част заради грешна хипотеза.',descriptionEn:'You may replace a good part because of a wrong hypothesis.',choices:[{id:'measure',labelBg:'Направи допълнително измерване',labelEn:'Take another measurement',quality:1,payDeltaCents:240,consequenceBg:'Допълнителната проверка намери истинската причина.',consequenceEn:'The extra check found the real cause.',skill:'technical'},{id:'replace',labelBg:'Следвай първата диагноза',labelEn:'Follow the first diagnosis',quality:-1,payDeltaCents:-280,consequenceBg:'Наложи се повторна диагностика.',consequenceEn:'The job required a second diagnostic pass.'}]},
    {id:'technical_handover',kind:'responsibility',titleBg:'Стажант иска помощ',titleEn:'An apprentice asks for help',descriptionBg:'Можеш да обясниш подхода или просто да дадеш отговора.',descriptionEn:'You can explain the approach or simply give the answer.',choices:[{id:'teach',labelBg:'Обясни логиката',labelEn:'Explain the reasoning',quality:1,payDeltaCents:180,consequenceBg:'Колегата разбра проблема и следващия път ще се справи сам.',consequenceEn:'The coworker understood the issue and can handle it next time.',skill:'leadership',needLevel:1},{id:'answer',labelBg:'Дай директно решението',labelEn:'Give the answer',quality:0,payDeltaCents:60,consequenceBg:'Задачата беше решена бързо.',consequenceEn:'The task was resolved quickly.'}]}
  ],
  resource:[
    {id:'resource_weather',kind:'problem',titleBg:'Условията се променят',titleEn:'Conditions are changing',descriptionBg:'Времето и теренът правят стандартния подход по-рисков.',descriptionEn:'Weather and terrain make the standard approach riskier.',choices:[{id:'adapt',labelBg:'Адаптирай работата',labelEn:'Adapt the work plan',quality:1,payDeltaCents:180,consequenceBg:'Промени темпото и избегна ненужен риск.',consequenceEn:'You adjusted pace and avoided unnecessary risk.',skill:'safety'},{id:'push',labelBg:'Запази темпото',labelEn:'Keep the pace',quality:-1,payDeltaCents:-240,consequenceBg:'Условията забавиха екипа и увеличиха риска.',consequenceEn:'Conditions slowed the team and increased risk.'}]},
    {id:'resource_yield',kind:'opportunity',titleBg:'По-добър добив от очакваното',titleEn:'Better yield than expected',descriptionBg:'Можеш да отделиш време за по-добра селекция или да приключиш по-бързо.',descriptionEn:'You can spend time selecting the best yield or finish sooner.',choices:[{id:'quality',labelBg:'Сортирай внимателно',labelEn:'Sort for quality',quality:1,payDeltaCents:220,consequenceBg:'Качеството повиши стойността на продукцията.',consequenceEn:'Better quality increased the value of the output.',skill:'agriculture',needLevel:1},{id:'volume',labelBg:'Приключи по-бързо',labelEn:'Finish faster',quality:0,payDeltaCents:80,consequenceBg:'Завърши задачата с добър обем.',consequenceEn:'You completed the task with solid volume.'}]}
  ]
};

const JOB_EVENTS: Record<string, EventDefinition[]> = {
  warehouse:[{id:'warehouse_unstable_pallet',kind:'problem',titleBg:'Нестабилен палет',titleEn:'Unstable pallet',descriptionBg:'Палетът изглежда зле подреден преди товарене.',descriptionEn:'A pallet is poorly stacked before loading.',choices:[{id:'restack',labelBg:'Пренареди палета',labelEn:'Re-stack the pallet',quality:1,payDeltaCents:220,consequenceBg:'Предотврати проблем при товаренето.',consequenceEn:'You prevented a loading problem.',skill:'safety'},{id:'leave',labelBg:'Остави го',labelEn:'Leave it',quality:-1,payDeltaCents:-300,consequenceBg:'Кашони паднаха при преместването.',consequenceEn:'Boxes fell during handling.'}]}],
  retail:[{id:'retail_price_dispute',kind:'problem',titleBg:'Разминаване в цената',titleEn:'Price mismatch',descriptionBg:'Етикетът на рафта е различен от цената на касата.',descriptionEn:'The shelf label differs from checkout.',choices:[{id:'check',labelBg:'Провери етикета',labelEn:'Check the label',quality:1,payDeltaCents:160,consequenceBg:'Откри грешен етикет и коригира ситуацията.',consequenceEn:'You found the wrong label and fixed the issue.',skill:'commerce'},{id:'insist',labelBg:'Настоявай за цената на касата',labelEn:'Insist on checkout price',quality:-1,payDeltaCents:-200,consequenceBg:'Клиентът поиска управител.',consequenceEn:'The customer asked for a manager.'}]}],
  dock:[{id:'dock_manifest_mismatch',kind:'problem',titleBg:'Товарът не съвпада',titleEn:'Cargo mismatch',descriptionBg:'Контейнерът е без очакваната маркировка.',descriptionEn:'A container lacks the expected marking.',choices:[{id:'hold',labelBg:'Задръж за проверка',labelEn:'Hold for verification',quality:1,payDeltaCents:320,consequenceBg:'Откри грешно насочен контейнер.',consequenceEn:'You caught a misrouted container.',skill:'logistics'},{id:'load',labelBg:'Продължи товаренето',labelEn:'Continue loading',quality:-1,payDeltaCents:-420,consequenceBg:'Товарът трябваше да бъде изваден по-късно.',consequenceEn:'The cargo later had to be removed.'}]}],
  kitchen:[{id:'kitchen_rush',kind:'problem',titleBg:'Поръчките идват наведнъж',titleEn:'Order rush',descriptionBg:'Една поръчка чака отдавна, друга е бърза, а третата е голяма.',descriptionEn:'One order is old, one is quick and one is large.',choices:[{id:'oldest',labelBg:'Първо най-старата',labelEn:'Oldest first',quality:1,payDeltaCents:220,consequenceBg:'Потокът се стабилизира.',consequenceEn:'The workflow stabilized.',skill:'cooking'},{id:'quick',labelBg:'Първо най-бързата',labelEn:'Quickest first',quality:0,payDeltaCents:80,consequenceBg:'Освободи място, но старата поръчка продължи да чака.',consequenceEn:'You freed space, but the oldest order kept waiting.'}]}]
};

export function eventPool(job: JobDefinition): EventDefinition[] {
  return [...(JOB_EVENTS[job.id] ?? []), ...GENERIC_EVENTS[job.archetype]];
}
