import { useEffect, useRef } from 'react';
import { Application, Container, Graphics } from 'pixi.js';
import raw from './procedural-street-v2.json';

type P=[number,number]; type RC='arterial'|'avenue'|'collector'|'local'; type MK='double-yellow'|'dash-white';
type BS='terracotta'|'concrete'|'brick'|'stucco'|'industrial'; type PK='lamp'|'hydrant'|'drain'|'dumpster'|'bench'|'bollard'|'utility'|'planter'|'meter'|'trash';
type Road={id:string;class:RC;width:number;sidewalk:number;lanes:number;centerline:P[];markings:{kind:MK;from:P;to:P}[]};
type Lot={id:string;points:P[];tone:'warm'|'cool'|'neutral'};
type Building={id:string;lot:string;footprint:P[];floors:number;style:BS;frontageEdge:number;storefronts:number;roofUnits:number;awning:boolean;windowColumns:number;balconyEvery:number;fireEscape:boolean;roofType:'flat'|'mechanical'};
type Scene={id:string;seed:number;sun:{direction:P;shadowStrength:number};palette:Record<string,string>;roads:Road[];junctionHints:P[];crosswalks:{center:P;length:number;span:number;angle:number;stripes:number}[];lots:Lot[];buildings:Building[];parking:{id:string;points:P[];spaces:number;orientation:'vertical'|'horizontal'}[];trees:{x:number;y:number;radius:number;occludes:boolean}[];props:{kind:PK;x:number;y:number}[]};
const source=raw as unknown as {canvas:{width:number;height:number};scene:Scene};

export function ProceduralStreetBackdrop({alerted}:{alerted:boolean}){
  const bg=useLayer('background',alerted), fg=useLayer('foreground',alerted);
  return <><div ref={bg} className="street-backdrop street-backdrop-pixi" style={{position:'absolute',inset:0,overflow:'hidden',pointerEvents:'none'}} aria-hidden="true"/><div ref={fg} className="street-backdrop street-backdrop-pixi-foreground" style={{position:'absolute',inset:0,zIndex:18,overflow:'hidden',pointerEvents:'none'}} aria-hidden="true"/></>;
}
function useLayer(layer:'background'|'foreground',alerted:boolean){
  const ref=useRef<HTMLDivElement|null>(null);
  useEffect(()=>{ if(ref.current===null)return; const host:HTMLDivElement=ref.current; let dead=false,ready=false; const app=new Application();
    void app.init({width:source.canvas.width,height:source.canvas.height,antialias:true,autoDensity:true,resolution:Math.min(window.devicePixelRatio||1,2),background:layer==='foreground'?'#000000':'#202522',backgroundAlpha:layer==='foreground'?0:1}).then(()=>{
      ready=true;if(dead){app.destroy(true);return} const canvas=app.canvas as HTMLCanvasElement; Object.assign(canvas.style,{position:'absolute',inset:'0',display:'block',width:'100%',height:'100%',objectFit:'cover'});canvas.setAttribute('aria-hidden','true');host.replaceChildren(canvas); layer==='background'?drawBackground(app.stage,source.scene,alerted):drawForeground(app.stage,source.scene,alerted);
    }).catch(e=>{console.error(`[street-v3] ${layer} renderer failed`,e);if(!dead)host.dataset.streetRendererError='true'});
    return()=>{dead=true;host.replaceChildren();if(ready)app.destroy(true)};
  },[layer,alerted]); return ref;
}
const pal=(s:Scene)=>Object.fromEntries(Object.entries(s.palette).map(([k,v])=>[k,parseInt(v.slice(1),16)])) as Record<string,number>;
function drawBackground(stage:Container,s:Scene,alerted:boolean){stage.removeChildren();const c=pal(s),r=rng(s.seed),j=junctions(s);ground(stage,c,r);lots(stage,s,c,r);sidewalks(stage,s,c,j);parking(stage,s,c);roads(stage,s,c,r,j);buildings(stage,s,c,alerted);streetLife(stage,s,c,false);const a=new Graphics();a.rect(0,0,1200,110).fill({color:0xf0d3a4,alpha:.025});a.rect(0,535,1200,165).fill({color:0x071012,alpha:.07});stage.addChild(a)}
function drawForeground(stage:Container,s:Scene,alerted:boolean){stage.removeChildren();const c=pal(s);awnings(stage,s,c,alerted);streetLife(stage,s,c,true)}
function ground(stage:Container,c:Record<string,number>,r:()=>number){const g=new Graphics();g.rect(0,0,1200,700).fill({color:c.concrete});for(let i=0;i<1350;i++){const x=r()*1200,y=r()*700;g.circle(x,y,.2+r()*.7).fill({color:r()>.6?c.concreteLight:c.concreteDark,alpha:.02+r()*.045})}for(let x=24;x<1200;x+=92)line(g,[x,0],[x-13,700],.7,c.concreteDark,.05);stage.addChild(g)}
function lots(stage:Container,s:Scene,c:Record<string,number>,r:()=>number){const tones={warm:0x5d5b54,cool:0x555f5e,neutral:0x595a54};for(const l of s.lots){const g=new Graphics(),b=bounds(l.points);poly(g,l.points).fill({color:tones[l.tone],alpha:.68}).stroke({width:1,color:c.concreteLight,alpha:.12});for(let y=b.minY+24;y<b.maxY;y+=42)line(g,[b.minX+8,y],[b.maxX-8,y-3],.7,c.concreteDark,.08);for(let i=0;i<12;i++){const p=sample(b,l.points,r);if(p)g.ellipse(p[0],p[1],5+r()*14,1+r()*4).fill({color:c.concreteDark,alpha:.02+r()*.03})}stage.addChild(g)}}
function sidewalks(stage:Container,s:Scene,c:Record<string,number>,j:P[]){const g=new Graphics();for(const rd of s.roads)strokePath(g,rd.centerline,rd.width+rd.sidewalk*2+10,c.sidewalk,1);for(const p of j){const rs=at(p,s.roads);g.circle(p[0],p[1],Math.max(30,...rs.map(x=>x.width*.37+x.sidewalk))).fill({color:c.sidewalk})}stage.addChild(g);const q=new Graphics();for(const rd of s.roads)segments(rd.centerline,(a,b)=>{const d=unit(a,b),n:P=[-d[1],d[0]],L=dist(a,b);for(let t=18;t<L-10;t+=34){const m=add(a,d,t);for(const side of [-1,1])line(q,add(m,n,side*(rd.width/2+5)),add(m,n,side*(rd.width/2+rd.sidewalk+3)),.7,c.sidewalkDark,.16)}});stage.addChild(q)}
function parking(stage:Container,s:Scene,c:Record<string,number>){for(const p of s.parking){if(!clearRoad(p.points,s.roads,5)||s.buildings.some(b=>polysHit(p.points,b.footprint)))continue;const g=new Graphics(),b=bounds(p.points);poly(g,p.points).fill({color:c.asphaltLight,alpha:.9}).stroke({width:2,color:c.curbDark,alpha:.6});const gap=(p.orientation==='vertical'?b.width:b.height)/p.spaces;for(let i=1;i<p.spaces;i++)p.orientation==='vertical'?line(g,[b.minX+gap*i,b.minY+7],[b.minX+gap*i,b.maxY-7],1.2,c.laneWhite,.32):line(g,[b.minX+7,b.minY+gap*i],[b.maxX-7,b.minY+gap*i],1.2,c.laneWhite,.32);for(let i=0;i<p.spaces;i++){const x=b.minX+b.width*(i+.5)/p.spaces;g.ellipse(x,b.maxY-15,9,2.4).fill({color:c.asphaltDark,alpha:.13});g.rect(x-5,b.maxY-10,10,2.5).fill({color:c.curbDark,alpha:.8})}stage.addChild(g)}}
function roads(stage:Container,s:Scene,c:Record<string,number>,r:()=>number,j:P[]){const under=new Graphics();for(const rd of s.roads)strokePath(under,rd.centerline,rd.width+9,c.curbDark,.92);stage.addChild(under);const curb=new Graphics();for(const rd of s.roads)strokePath(curb,rd.centerline,rd.width+5,c.curb,.82);stage.addChild(curb);const a=new Graphics();for(const rd of s.roads){strokePath(a,rd.centerline,rd.width,c.asphalt,1);strokePath(a,rd.centerline,Math.max(8,rd.width-10),c.asphaltLight,.045)}for(const p of j){const rs=at(p,s.roads);a.circle(p[0],p[1],Math.max(26,...rs.map(x=>x.width*.4))).fill({color:c.asphalt})}stage.addChild(a);asphalt(stage,s,c,r,j);const m=new Graphics();for(const rd of s.roads)for(const x of rd.markings)mark(m,x,c);for(const x of s.crosswalks)crosswalk(m,x,c.laneWhite);stage.addChild(m)}
function asphalt(stage:Container,s:Scene,c:Record<string,number>,r:()=>number,j:P[]){const g=new Graphics();for(let i=0;i<1750;i++){const p:P=[r()*1200,r()*700];if(onRoad(p,s.roads,j))g.circle(p[0],p[1],.2+r()*.6).fill({color:r()>.68?c.asphaltLight:c.asphaltDark,alpha:.03+r()*.05})}for(const rd of s.roads)segments(rd.centerline,(a,b)=>{const d=unit(a,b),n:P=[-d[1],d[0]],L=dist(a,b);for(const side of [-1,1])line(g,add(a,n,side*(rd.width/2-2)),add(b,n,side*(rd.width/2-2)),2,c.asphaltDark,.22);for(let i=0;i<Math.max(4,Math.floor(L/150));i++){const m=add(add(a,d,r()*L),n,(r()-.5)*rd.width*.65),len=25+r()*70;line(g,add(m,d,-len/2),add(m,d,len/2),1+r()*3,r()>.5?c.asphaltDark:c.asphaltLight,.025+r()*.05)}for(let i=0;i<Math.max(1,Math.floor(L/280));i++){const m=add(add(a,d,(.2+r()*.6)*L),n,(r()-.5)*rd.width*.4),pl=18+r()*36,pw=6+r()*12;poly(g,[add(add(m,d,-pl/2),n,-pw/2),add(add(m,d,pl/2),n,-pw/2),add(add(m,d,pl/2),n,pw/2),add(add(m,d,-pl/2),n,pw/2)]).fill({color:c.patch,alpha:.15}).stroke({width:.7,color:c.asphaltDark,alpha:.2})}});for(let i=0;i<45;i++){const p:P=[r()*1200,r()*700];if(!onRoad(p,s.roads,j))continue;const A=r()*Math.PI*2,p1:P=[p[0]+Math.cos(A)*(5+r()*9),p[1]+Math.sin(A)*(5+r()*9)],B=A+(r()-.5)*.7,p2:P=[p1[0]+Math.cos(B)*(4+r()*9),p1[1]+Math.sin(B)*(4+r()*9)];g.moveTo(...p).lineTo(...p1).lineTo(...p2).stroke({width:.6+r()*.4,color:c.asphaltDark,alpha:.18+r()*.1})}stage.addChild(g);hardware(stage,s,c)}
function hardware(stage:Container,s:Scene,c:Record<string,number>){const g=new Graphics();s.roads.forEach((rd,i)=>{const a=rd.centerline[0]!,b=rd.centerline.at(-1)!;if(!b)return;const d=unit(a,b),n:P=[-d[1],d[0]],L=dist(a,b);for(const t of [.25,.7]){const p=add(add(a,d,L*t),n,(i%2?1:-1)*rd.width*.22);g.circle(p[0],p[1],5.5).fill({color:c.asphaltDark,alpha:.85}).stroke({width:1,color:c.metal,alpha:.7});g.circle(p[0],p[1],3).stroke({width:.7,color:c.metal,alpha:.4})}});stage.addChild(g)}
function mark(g:Graphics,m:Road['markings'][number],c:Record<string,number>){if(m.kind==='double-yellow'){const n=normal(m.from,m.to);line(g,add(m.from,n,-2.1),add(m.to,n,-2.1),1.25,c.laneYellow,.62);line(g,add(m.from,n,2.1),add(m.to,n,2.1),1.25,c.laneYellow,.62)}else dashed(g,m.from,m.to,13,14,1.45,c.laneWhite,.42)}
function crosswalk(g:Graphics,x:Scene['crosswalks'][number],color:number){const [cx,cy]=x.center,A=x.angle*Math.PI/180,d:P=[Math.cos(A),Math.sin(A)],n:P=[-d[1],d[0]],step=x.length/x.stripes,w=x.length/(x.stripes*2);for(let i=0;i<x.stripes;i++){const m:P=[cx+d[0]*(-x.length/2+step*(i+.5)),cy+d[1]*(-x.length/2+step*(i+.5))];poly(g,[add(add(m,d,-w/2),n,-x.span/2),add(add(m,d,w/2),n,-x.span/2),add(add(m,d,w/2),n,x.span/2),add(add(m,d,-w/2),n,x.span/2)]).fill({color,alpha:i%3===1?.48:.58})}}
function buildings(stage:Container,s:Scene,c:Record<string,number>,alerted:boolean){const lots=new Map(s.lots.map(x=>[x.id,x])),accepted:Building[]=[];for(const b of s.buildings){const lot=lots.get(b.lot);if(!lot||!b.footprint.every(p=>inside(p,lot.points))||!clearRoad(b.footprint,s.roads,5)||accepted.some(x=>polysHit(x.footprint,b.footprint)))continue;accepted.push(b);building(stage,b,s,c,alerted&&b.id==='corner_store')}}
function building(stage:Container,b:Building,s:Scene,c:Record<string,number>,alert:boolean){const st=style(b.style,alert),h=8+b.floors*5.8,shift:P=[-h*.38,-h],roof=b.footprint.map(p=>sum(p,shift)),cent=centroid(b.footprint);const sh=new Graphics();for(let k=3;k>=1;k--){const m=h*(1+k*.18);poly(sh,b.footprint.map(p=>[p[0]+s.sun.direction[0]*m,p[1]+s.sun.direction[1]*m] as P)).fill({color:c.shadow,alpha:s.sun.shadowStrength*(.1+k*.055)})}stage.addChild(sh);const w=new Graphics();for(let e=0;e<b.footprint.length;e++){const ba=b.footprint[e]!,bb=b.footprint[(e+1)%b.footprint.length]!,ra=roof[e]!,rb=roof[(e+1)%roof.length]!,mid:P=[(ba[0]+bb[0])/2,(ba[1]+bb[1])/2];if(mid[1]<cent[1]-2&&mid[0]<cent[0]-2)continue;poly(w,[ra,rb,bb,ba]).fill({color:mid[1]>=cent[1]?st.front:st.side});facade(w,b,e,ra,rb,ba,bb,st,c)}stage.addChild(w);const g=new Graphics(),inset=shrink(roof,5.5);poly(g,roof).fill({color:st.roof}).stroke({width:1.5,color:st.trim,alpha:.54});poly(g,inset).stroke({width:2,color:st.trim,alpha:.2});roofDetail(g,b,roof,inset,st,c,s.seed);stage.addChild(g)}
function facade(g:Graphics,b:Building,e:number,ra:P,rb:P,ba:P,bb:P,st:ReturnType<typeof style>,c:Record<string,number>){const L=dist(ba,bb);if(L<24)return;const front=e===Math.min(b.frontageEdge,b.footprint.length-1),cols=Math.max(2,Math.min(b.windowColumns,Math.floor(L/22)));for(let f=1;f<b.floors;f++)line(g,mix(ra,ba,f/b.floors),mix(rb,bb,f/b.floors),.8,st.trim,.18);for(let f=0;f<b.floors;f++){const top=(f+.18)/b.floors,bot=(f+.76)/b.floors,ground=f===b.floors-1,count=ground&&front&&b.storefronts?b.storefronts:cols;for(let k=0;k<count;k++){const l=(k+.16)/count,r=(k+.84)/count,ta=mix(ra,ba,top),tb=mix(rb,bb,top),da=mix(ra,ba,bot),db=mix(rb,bb,bot),p1=mix(ta,tb,l),p2=mix(ta,tb,r),p3=mix(da,db,r),p4=mix(da,db,l),shop=ground&&front&&b.storefronts>0;poly(g,[p1,p2,p3,p4]).fill({color:shop?c.glass:st.window,alpha:shop?.88:.68}).stroke({width:.65,color:shop?c.glassLight:st.trim,alpha:.36});if(shop)line(g,mix(p1,p2,.5),mix(p4,p3,.5),.6,st.trim,.45);if(!ground&&b.balconyEvery>0&&(k+1)%b.balconyEvery===0){line(g,p4,p3,2,c.metal,.72);line(g,[p4[0],p4[1]+2],[p3[0],p3[1]+2],.7,st.trim,.45)}}}if(front){const a=mix(mix(ra,ba,.78),mix(rb,bb,.78),.5),d=mix(ba,bb,.5);line(g,a,d,6.5,c.asphaltDark,.78);line(g,a,d,4.5,st.window,.78)}if(b.fireEscape&&!front){const a=mix(ra,rb,.78),d=mix(ba,bb,.78),n=normal(a,d);line(g,a,d,1.4,c.metal,.7);for(let t=.15;t<.9;t+=.12)line(g,add(mix(a,d,t),n,-4),add(mix(a,d,t),n,4),.7,c.metal,.6)}if(b.style==='brick')for(let t=.12;t<.9;t+=.09)line(g,mix(ra,ba,t),mix(rb,bb,t),.45,st.dark,.12)}
function roofDetail(g:Graphics,b:Building,roof:P[],inset:P[],st:ReturnType<typeof style>,c:Record<string,number>,seed:number){const r=rng(seed+hash(b.id)),box=bounds(roof);for(let i=0;i<24;i++){const p=sample(box,roof,r);if(p)g.ellipse(p[0],p[1],2+r()*9,1+r()*3).fill({color:r()>.55?st.dark:st.light,alpha:.025+r()*.05})}for(let i=0;i<b.roofUnits+(b.roofType==='mechanical'?2:0);i++){const p=sample(box,inset,r);if(!p)continue;const w=11+r()*16,h=7+r()*10;g.rect(p[0]-w/2+2,p[1]-h/2+3,w,h).fill({color:c.shadow,alpha:.2});g.rect(p[0]-w/2,p[1]-h/2,w,h).fill({color:c.metal}).stroke({width:.7,color:st.trim,alpha:.4});g.circle(p[0],p[1],Math.min(w,h)*.23).stroke({width:.8,color:c.asphaltDark,alpha:.7})}}
function awnings(stage:Container,s:Scene,c:Record<string,number>,alerted:boolean){const g=new Graphics();for(const b of s.buildings){if(!b.awning||!clearRoad(b.footprint,s.roads,5))continue;const h=8+b.floors*5.8,shift:P=[-h*.38,-h],e=Math.min(b.frontageEdge,b.footprint.length-1),ba=b.footprint[e]!,bb=b.footprint[(e+1)%b.footprint.length]!,a=mix(sum(ba,shift),ba,.76),d=mix(sum(bb,shift),bb,.76),st=style(b.style,alerted&&b.id==='corner_store');line(g,[a[0]+2,a[1]+4],[d[0]+2,d[1]+4],6.5,c.shadow,.18);line(g,a,d,5.3,st.awning,.96);line(g,[a[0],a[1]-1.5],[d[0],d[1]-1.5],1,st.trim,.48)}stage.addChild(g)}
function streetLife(stage:Container,s:Scene,c:Record<string,number>,fg:boolean){for(const t of s.trees){if(fg&&!t.occludes)continue;if(roadGap([t.x,t.y],s.roads)<t.radius+3||s.buildings.some(b=>inside([t.x,t.y],b.footprint)))continue;if(fg)crown(stage,t,c,s.seed);else tree(stage,t,c,s.seed)}if(fg)return;for(const p of s.props){if(s.buildings.some(b=>inside([p.x,p.y],b.footprint)))continue;if(p.kind!=='drain'&&roadGap([p.x,p.y],s.roads)<1)continue;prop(stage,p,c)}}
function tree(stage:Container,t:Scene['trees'][number],c:Record<string,number>,seed:number){const g=new Graphics();g.ellipse(t.x+9,t.y+10,t.radius*1.15,t.radius*.43).fill({color:c.shadow,alpha:.27});g.rect(t.x-1.7,t.y-1,3.4,t.radius*.92).fill({color:0x584533,alpha:.96});stage.addChild(g);if(!t.occludes)crown(stage,t,c,seed);else{const q=new Graphics();q.circle(t.x,t.y-t.radius*.15,t.radius*.55).fill({color:c.foliageDark,alpha:.78});stage.addChild(q)}}
function crown(stage:Container,t:Scene['trees'][number],c:Record<string,number>,seed:number){const g=new Graphics(),r=rng(seed+Math.round(t.x*17+t.y*29));for(let i=0;i<8;i++){const A=i/8*Math.PI*2+r()*.35,D=t.radius*(.18+r()*.4),R=t.radius*(.38+r()*.25),x=t.x+Math.cos(A)*D,y=t.y-t.radius*.38+Math.sin(A)*D*.65,col=i%3===0?c.foliageLight:i%2===0?c.foliageDark:c.foliage;g.circle(x,y,R).fill({color:col,alpha:.88+r()*.1})}g.circle(t.x-t.radius*.2,t.y-t.radius*.7,t.radius*.24).fill({color:c.foliageLight,alpha:.6});stage.addChild(g)}
function prop(stage:Container,p:Scene['props'][number],c:Record<string,number>){const g=new Graphics(),x=p.x,y=p.y;if(p.kind==='lamp'){g.ellipse(x+4,y+8,7,2.4).fill({color:c.shadow,alpha:.24});line(g,[x,y+8],[x,y-19],2.6,c.metal,.95);line(g,[x,y-18],[x+6,y-21],2,c.metal,.9);g.circle(x+7,y-22,3.4).fill({color:0x6b7475})}else if(p.kind==='hydrant'){g.rect(x-3.5,y-7,7,11).fill({color:0x9b4b3e});g.rect(x-5,y-4,10,3).fill({color:0xb55d4c});g.circle(x,y-7,3.5).fill({color:0xa95243})}else if(p.kind==='drain'){g.rect(x-7,y-2.5,14,5).fill({color:c.asphaltDark}).stroke({width:.7,color:c.metal,alpha:.7})}else if(p.kind==='dumpster'){g.rect(x-10,y-8,21,15).fill({color:0x3b5548}).stroke({width:1,color:0x263a31,alpha:.85})}else if(p.kind==='bench'){g.rect(x-10,y-3,20,4).fill({color:0x6c5841});g.rect(x-10,y-9,20,3).fill({color:0x766047})}else if(p.kind==='bollard')g.rect(x-1.7,y-6,3.4,10).fill({color:c.metal});else if(p.kind==='utility')g.rect(x-7,y-11,14,20).fill({color:0x4e5b55}).stroke({width:.8,color:c.metal,alpha:.7});else if(p.kind==='planter'){g.rect(x-8,y-1,16,8).fill({color:0x63564a});g.circle(x-4,y-5,5).fill({color:c.foliage});g.circle(x+3,y-6,6).fill({color:c.foliageLight})}else if(p.kind==='meter'){line(g,[x,y+5],[x,y-7],1.5,c.metal,.85);g.roundRect(x-2.5,y-10,5,5,1).fill({color:0x647074})}else g.rect(x-4,y-5,8,10).fill({color:0x3f5550});stage.addChild(g)}
function style(s:BS,a:boolean){if(a)return{roof:0x705149,front:0x5a3e36,side:0x3f312d,trim:0xba8e79,window:0x31545b,awning:0x71473d,light:0xb89578,dark:0x30251f};return({terracotta:{roof:0x776252,front:0x655044,side:0x493b35,trim:0xb6a083,window:0x31535b,awning:0x74533f,light:0xb9a48c,dark:0x382d27},concrete:{roof:0x596567,front:0x4a5a5b,side:0x344447,trim:0x929f9a,window:0x315961,awning:0x465d61,light:0xa0aaa4,dark:0x2d393b},brick:{roof:0x77564b,front:0x68473d,side:0x4b3732,trim:0xa98873,window:0x32555d,awning:0x67483c,light:0xb3917d,dark:0x342720},stucco:{roof:0x786c5d,front:0x6d6255,side:0x524a41,trim:0xb8a990,window:0x34585e,awning:0x7d5e45,light:0xc0b49c,dark:0x3d362f},industrial:{roof:0x555b58,front:0x454d49,side:0x303936,trim:0x8a9088,window:0x324c50,awning:0x4f5753,light:0x989d93,dark:0x2b302e}} as const)[s]}
function junctions(s:Scene){const out:P[]=s.junctionHints.map(p=>[...p] as P);for(let i=0;i<s.roads.length;i++)for(let k=i+1;k<s.roads.length;k++)pairs(s.roads[i]!.centerline,s.roads[k]!.centerline,(a,b,c,d)=>{const p=intersect(a,b,c,d);if(p)out.push(p)});return out.filter((p,i)=>out.findIndex(q=>dist(p,q)<10)===i)}
const at=(p:P,r:Road[])=>r.filter(x=>dPolyline(p,x.centerline)<=x.width/2+x.sidewalk+14);
function onRoad(p:P,r:Road[],j:P[]){if(r.some(x=>dPolyline(p,x.centerline)<=x.width/2))return true;return j.some(q=>dist(p,q)<=Math.max(26,...at(q,r).map(x=>x.width*.4)))}
function clearRoad(ps:P[],rs:Road[],gap:number){for(const r of rs){const need=r.width/2+gap;if(ps.some(p=>dPolyline(p,r.centerline)<need))return false;for(let i=0;i<ps.length;i++)for(let k=0;k<r.centerline.length-1;k++)if(intersect(ps[i]!,ps[(i+1)%ps.length]!,r.centerline[k]!,r.centerline[k+1]!))return false}return true}
function roadGap(p:P,rs:Road[]){return Math.min(...rs.map(r=>dPolyline(p,r.centerline)-r.width/2))}
function polysHit(a:P[],b:P[]){if(a.some(p=>inside(p,b))||b.some(p=>inside(p,a)))return true;for(let i=0;i<a.length;i++)for(let k=0;k<b.length;k++)if(intersect(a[i]!,a[(i+1)%a.length]!,b[k]!,b[(k+1)%b.length]!))return true;return false}
function strokePath(g:Graphics,p:P[],w:number,c:number,a:number){if(p.length<2)return;g.moveTo(...p[0]!);for(let i=1;i<p.length;i++)g.lineTo(...p[i]!);g.stroke({width:w,color:c,alpha:a,cap:'round',join:'round'})}
function line(g:Graphics,a:P,b:P,w:number,c:number,alpha:number){g.moveTo(...a).lineTo(...b).stroke({width:w,color:c,alpha,cap:'round'})}
function dashed(g:Graphics,a:P,b:P,dash:number,gap:number,w:number,c:number,alpha:number){const L=dist(a,b),u=unit(a,b);for(let t=0;t<L;t+=dash+gap)line(g,add(a,u,t),add(a,u,Math.min(L,t+dash)),w,c,alpha)}
function poly(g:Graphics,p:P[]){if(!p.length)return g;g.moveTo(...p[0]!);for(let i=1;i<p.length;i++)g.lineTo(...p[i]!);g.closePath();return g}
function inside(p:P,ps:P[]){if(ps.some((a,i)=>dSeg(p,a,ps[(i+1)%ps.length]!)<.35))return true;let yes=false;for(let i=0,j=ps.length-1;i<ps.length;j=i++){const [x,y]=ps[i]!,[X,Y]=ps[j]!;if((y>p[1])!==(Y>p[1])&&p[0]<(X-x)*(p[1]-y)/((Y-y)||.0001)+x)yes=!yes}return yes}
function bounds(ps:P[]){const xs=ps.map(p=>p[0]),ys=ps.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);return{minX,maxX,minY,maxY,width:maxX-minX,height:maxY-minY}}
function sample(b:ReturnType<typeof bounds>,ps:P[],r:()=>number){for(let i=0;i<24;i++){const p:P=[b.minX+8+r()*Math.max(1,b.width-16),b.minY+8+r()*Math.max(1,b.height-16)];if(inside(p,ps))return p}return null}
function centroid(ps:P[]):P{const s=ps.reduce((q,p)=>[q[0]+p[0],q[1]+p[1]] as P,[0,0] as P);return[s[0]/ps.length,s[1]/ps.length]}
function shrink(ps:P[],n:number){const c=centroid(ps);return ps.map(p=>{const d=Math.max(1,dist(p,c)),r=Math.max(0,(d-n)/d);return[c[0]+(p[0]-c[0])*r,c[1]+(p[1]-c[1])*r] as P})}
function segments(ps:P[],fn:(a:P,b:P)=>void){for(let i=0;i<ps.length-1;i++)fn(ps[i]!,ps[i+1]!)}function pairs(a:P[],b:P[],fn:(a:P,b:P,c:P,d:P)=>void){for(let i=0;i<a.length-1;i++)for(let k=0;k<b.length-1;k++)fn(a[i]!,a[i+1]!,b[k]!,b[k+1]!)}
function intersect(a:P,b:P,c:P,d:P):P|null{const den=(a[0]-b[0])*(c[1]-d[1])-(a[1]-b[1])*(c[0]-d[0]);if(Math.abs(den)<.0001)return null;const A=a[0]*b[1]-a[1]*b[0],B=c[0]*d[1]-c[1]*d[0],p:P=[(A*(c[0]-d[0])-(a[0]-b[0])*B)/den,(A*(c[1]-d[1])-(a[1]-b[1])*B)/den];return onSeg(p,a,b)&&onSeg(p,c,d)?p:null}
const onSeg=(p:P,a:P,b:P)=>p[0]>=Math.min(a[0],b[0])-.01&&p[0]<=Math.max(a[0],b[0])+.01&&p[1]>=Math.min(a[1],b[1])-.01&&p[1]<=Math.max(a[1],b[1])+.01;
function dPolyline(p:P,l:P[]){let x=Infinity;for(let i=0;i<l.length-1;i++)x=Math.min(x,dSeg(p,l[i]!,l[i+1]!));return x}function dSeg(p:P,a:P,b:P){const dx=b[0]-a[0],dy=b[1]-a[1],L=dx*dx+dy*dy;if(!L)return dist(p,a);const t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/L));return Math.hypot(p[0]-a[0]-dx*t,p[1]-a[1]-dy*t)}
const dist=(a:P,b:P)=>Math.hypot(b[0]-a[0],b[1]-a[1]);const unit=(a:P,b:P):P=>{const d=Math.max(.001,dist(a,b));return[(b[0]-a[0])/d,(b[1]-a[1])/d]};const normal=(a:P,b:P):P=>{const u=unit(a,b);return[-u[1],u[0]]};const add=(p:P,v:P,n:number):P=>[p[0]+v[0]*n,p[1]+v[1]*n];const sum=(a:P,b:P):P=>[a[0]+b[0],a[1]+b[1]];const mix=(a:P,b:P,t:number):P=>[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t];
function hash(s:string){let v=0;for(let i=0;i<s.length;i++)v=Math.imul(31,v)+s.charCodeAt(i)|0;return Math.abs(v)}function rng(seed:number){let v=seed>>>0;return()=>{v+=0x6D2B79F5;let x=v;x=Math.imul(x^x>>>15,x|1);x^=x+Math.imul(x^x>>>7,x|61);return((x^x>>>14)>>>0)/4294967296}}
