export function worldMapCopy(locale: string) {
  const bg = locale === 'bg';
  return bg ? {
    map: 'Карта на SOL DORADO',
    openMap: 'Карта',
    backToStreet: 'Обратно на улицата',
    region: 'Регион',
    settlement: 'Населено място',
    zone: 'Зона',
    district: 'Квартал',
    street: 'Улица',
    current: 'Текущо местоположение',
    playable: 'Достъпна улица',
    planned: 'Все още недостъпна',
    currentStreet: 'В момента си на тази улица.',
    parcelOwnable: 'Потенциален имот',
    parcelPublic: 'Публичен / системен обект',
    institution: 'Институция / услуга',
    noStreets: 'Тази част от уличната мрежа още не е детайлно изградена.',
    mapLoadError: 'Картата не можа да се зареди. Провери дали world migrations са изпълнени.',
    hierarchyHint: 'Избери област директно от картата, за да увеличиш мащаба.',
    streetHint: 'Избери достъпен уличен сегмент. Текущият се отваря директно; до друг достижим сегмент можеш да пътуваш по уличната мрежа.',
    openStreet: 'Отвори улицата',
    travelHere: 'Пътувай дотук',
    travelling: 'Пътуване…',
    unavailable: 'Недостъпно',
    notAccessible: 'Тази улица все още не е достъпна за игра.',
    noDirectRoute: 'Няма пешеходен маршрут от текущата ти улица.',
    travelDetail: 'Пешеходен маршрут: {distance} m. Пътуването променя реалното ти местоположение.',
    travelSuccess: 'Пристигна на избраната улица.',
    travelFailed: 'Не успя да стигнеш до избраната улица.',
    notEnoughEnergy: 'Нямаш достатъчно енергия за този маршрут.',
    walk: 'пеша'
  } : {
    map: 'SOL DORADO Map',
    openMap: 'Map',
    backToStreet: 'Back to street',
    region: 'Region',
    settlement: 'Settlement',
    zone: 'Zone',
    district: 'District',
    street: 'Street',
    current: 'Current location',
    playable: 'Playable street',
    planned: 'Not accessible yet',
    currentStreet: 'You are currently on this street.',
    parcelOwnable: 'Potential property',
    parcelPublic: 'Public / system site',
    institution: 'Institution / service',
    noStreets: 'This part of the street network has not been authored in detail yet.',
    mapLoadError: 'The world map could not load. Check that the world migrations have been applied.',
    hierarchyHint: 'Select an area directly on the map to zoom into it.',
    streetHint: 'Select a playable street segment. Open the current one directly or travel to another reachable segment through the street network.',
    openStreet: 'Open street',
    travelHere: 'Travel here',
    travelling: 'Travelling…',
    unavailable: 'Unavailable',
    notAccessible: 'This street is not accessible for gameplay yet.',
    noDirectRoute: 'There is no walking route from your current street.',
    travelDetail: 'Walking route: {distance} m. Travelling changes your real player location.',
    travelSuccess: 'You arrived at the selected street.',
    travelFailed: 'You could not reach the selected street.',
    notEnoughEnergy: 'You do not have enough energy for this route.',
    walk: 'walk'
  };
}
