import type { PoolClient } from 'pg';
import type { Database } from '../db.js';
import { RealEstateMutationResultSchema, RealEstateStateSchema, type PropertyKind, type RealEstateState } from '@sol-dorado/contracts/real-estate';

type Queryable = Database | PoolClient;
export class RealEstateCommandError extends Error { constructor(public readonly code:string, public readonly status:number){super(code);} }

const CLIENTS = [
  {id:'cole',name:'Jason Cole',budgetMinCents:18000000,budgetMaxCents:26000000,kind:'apartment' as PropertyKind,district:'Downtown',parkingRequired:1},
  {id:'ortiz',name:'Maya Ortiz',budgetMinCents:15000000,budgetMaxCents:21000000,kind:'house' as PropertyKind,district:'Southside',parkingRequired:1},
  {id:'chen',name:'Leo Chen',budgetMinCents:40000000,budgetMaxCents:55000000,kind:'warehouse' as PropertyKind,district:'Harbor',parkingRequired:0}
];

export function scorePropertyMatch(client:(typeof CLIENTS)[number], property:{priceCents:number;district:string;kind:PropertyKind;parkingSpaces:number}) {
  let score=0;
  if(property.priceCents>=client.budgetMinCents&&property.priceCents<=client.budgetMaxCents) score+=45;
  if(property.district===client.district) score+=25;
  if(property.kind===client.kind) score+=20;
  if(property.parkingSpaces>=client.parkingRequired) score+=10;
  return score;
}

async function ensureCareer(db:Queryable,playerId:string){await db.query(`INSERT INTO real_estate_careers(player_id) VALUES($1) ON CONFLICT(player_id) DO NOTHING`,[playerId]);}
async function log(db:Queryable,playerId:string,kind:string,bg:string,en:string){await db.query(`INSERT INTO real_estate_activity(player_id,kind,summary_bg,summary_en) VALUES($1,$2,$3,$4)`,[playerId,kind,bg,en]);}

export async function getRealEstateState(db:Queryable,playerId:string):Promise<RealEstateState>{
  await ensureCareer(db,playerId);
  const [listings,owned,access,viewed,career,progress,activity]=await Promise.all([
    db.query(`SELECT id,property_key,name_bg,name_en,kind,district,street_segment,price_cents,listed,bedrooms,parking_spaces,storage_slots,agent_name,description_bg,description_en FROM real_estate_properties ORDER BY price_cents`),
    db.query(`SELECT property_id,is_primary_residence,locked,storage_used,tenant_name,monthly_rent_cents FROM player_properties WHERE player_id=$1`,[playerId]),
    db.query(`SELECT id,property_id,name,role FROM property_access WHERE player_id=$1 ORDER BY created_at`,[playerId]),
    db.query(`SELECT property_id FROM property_viewings WHERE player_id=$1`,[playerId]),
    db.query(`SELECT license_stage,employed,reputation,commission_earned_cents FROM real_estate_careers WHERE player_id=$1`,[playerId]),
    db.query(`SELECT client_key,status FROM real_estate_client_progress WHERE player_id=$1`,[playerId]),
    db.query(`SELECT id,kind,summary_bg,summary_en,created_at FROM real_estate_activity WHERE player_id=$1 ORDER BY created_at DESC LIMIT 30`,[playerId])
  ]);
  const props=listings.rows.map((r:any)=>({id:r.id,key:r.property_key,nameBg:r.name_bg,nameEn:r.name_en,kind:r.kind,district:r.district,streetSegment:r.street_segment,priceCents:Number(r.price_cents),listed:r.listed,bedrooms:r.bedrooms,parkingSpaces:r.parking_spaces,storageSlots:r.storage_slots,agentName:r.agent_name,descriptionBg:r.description_bg,descriptionEn:r.description_en}));
  const ownedRows=owned.rows.map((o:any)=>({property:props.find(p=>p.id===o.property_id)!,isPrimaryResidence:o.is_primary_residence,locked:o.locked,storageUsed:o.storage_used,access:access.rows.filter((a:any)=>a.property_id===o.property_id).map((a:any)=>({id:a.id,name:a.name,role:a.role})),tenantName:o.tenant_name,monthlyRentCents:Number(o.monthly_rent_cents)}));
  const c=career.rows[0]; const status=new Map(progress.rows.map((r:any)=>[r.client_key,r.status]));
  return RealEstateStateSchema.parse({listings:props,owned:ownedRows,viewedPropertyIds:viewed.rows.map((r:any)=>r.property_id),career:{licenseStage:c.license_stage,employed:c.employed,reputation:c.reputation,commissionEarnedCents:Number(c.commission_earned_cents)},clients:CLIENTS.map(x=>({...x,status:status.get(x.id)??'new'})),activity:activity.rows.map((r:any)=>({id:r.id,kind:r.kind,summaryBg:r.summary_bg,summaryEn:r.summary_en,createdAt:new Date(r.created_at).toISOString()}))});
}
async function result(db:Queryable,playerId:string,message:string){const cash=await db.query(`SELECT cash_cents FROM player_state WHERE player_id=$1`,[playerId]);return RealEstateMutationResultSchema.parse({state:await getRealEstateState(db,playerId),cashCents:Number(cash.rows[0]?.cash_cents??0),message});}

export async function recordViewing(db:Database,playerId:string,propertyId:string){
  const p=await db.query(`SELECT id FROM real_estate_properties WHERE id=$1 AND listed=true`,[propertyId]); if(!p.rowCount)throw new RealEstateCommandError('property_not_listed',404);
  await db.query(`INSERT INTO property_viewings(player_id,property_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[playerId,propertyId]); await log(db,playerId,'viewing','Завършен оглед на имот.','Property viewing completed.'); return result(db,playerId,'viewing_completed');
}
export async function makeOffer(db:Database,playerId:string,propertyId:string,amountCents:number){
 const client=await db.connect(); try{await client.query('BEGIN'); const p=(await client.query(`SELECT * FROM real_estate_properties WHERE id=$1 FOR UPDATE`,[propertyId])).rows[0]; if(!p||!p.listed)throw new RealEstateCommandError('property_not_listed',404); const viewed=await client.query(`SELECT 1 FROM property_viewings WHERE player_id=$1 AND property_id=$2`,[playerId,propertyId]); if(!viewed.rowCount)throw new RealEstateCommandError('viewing_required',409); if(amountCents<Math.round(Number(p.price_cents)*0.97))throw new RealEstateCommandError('offer_rejected',409); const state=(await client.query(`SELECT cash_cents FROM player_state WHERE player_id=$1 FOR UPDATE`,[playerId])).rows[0]; if(!state||Number(state.cash_cents)<amountCents)throw new RealEstateCommandError('insufficient_cash',409); await client.query(`UPDATE player_state SET cash_cents=cash_cents-$2,version=version+1,updated_at=now() WHERE player_id=$1`,[playerId,amountCents]); await client.query(`INSERT INTO player_properties(player_id,property_id) VALUES($1,$2)`,[playerId,propertyId]); await client.query(`UPDATE real_estate_properties SET listed=false WHERE id=$1`,[propertyId]); await log(client,playerId,'purchase',`Купен имот ${p.name_bg} за $${Math.round(amountCents/100).toLocaleString('en-US')}.`,`Purchased ${p.name_en} for $${Math.round(amountCents/100).toLocaleString('en-US')}.`); await client.query('COMMIT'); return result(db,playerId,'property_purchased'); }catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
}
export async function setPrimaryResidence(db:Database,playerId:string,propertyId:string){const p=await db.query(`SELECT rp.kind FROM player_properties pp JOIN real_estate_properties rp ON rp.id=pp.property_id WHERE pp.player_id=$1 AND pp.property_id=$2`,[playerId,propertyId]); if(!p.rowCount)throw new RealEstateCommandError('property_not_owned',404); if(!['apartment','house'].includes(p.rows[0].kind))throw new RealEstateCommandError('not_residential',409); await db.query(`UPDATE player_properties SET is_primary_residence=false WHERE player_id=$1`,[playerId]); await db.query(`UPDATE player_properties SET is_primary_residence=true WHERE player_id=$1 AND property_id=$2`,[playerId,propertyId]); return result(db,playerId,'primary_residence_updated');}
export async function togglePropertyLock(db:Database,playerId:string,propertyId:string){const q=await db.query(`UPDATE player_properties SET locked=NOT locked WHERE player_id=$1 AND property_id=$2 RETURNING property_id`,[playerId,propertyId]); if(!q.rowCount)throw new RealEstateCommandError('property_not_owned',404); return result(db,playerId,'property_lock_updated');}
export async function addPropertyAccess(db:Database,playerId:string,propertyId:string,name:string,role:string){const own=await db.query(`SELECT 1 FROM player_properties WHERE player_id=$1 AND property_id=$2`,[playerId,propertyId]); if(!own.rowCount)throw new RealEstateCommandError('property_not_owned',404); await db.query(`INSERT INTO property_access(player_id,property_id,name,role) VALUES($1,$2,$3,$4)`,[playerId,propertyId,name,role]); return result(db,playerId,'property_access_added');}
export async function removePropertyAccess(db:Database,playerId:string,propertyId:string,accessId:string){await db.query(`DELETE FROM property_access WHERE id=$1 AND player_id=$2 AND property_id=$3`,[accessId,playerId,propertyId]); return result(db,playerId,'property_access_removed');}
export async function createLease(db:Database,playerId:string,propertyId:string,tenantName:string,monthlyRentCents:number){const q=await db.query(`UPDATE player_properties SET tenant_name=$3,monthly_rent_cents=$4 WHERE player_id=$1 AND property_id=$2 RETURNING property_id`,[playerId,propertyId,tenantName,monthlyRentCents]); if(!q.rowCount)throw new RealEstateCommandError('property_not_owned',404); await log(db,playerId,'lease',`Договор за наем: ${tenantName}.`,`Lease created: ${tenantName}.`); return result(db,playerId,'lease_created');}
export async function endLease(db:Database,playerId:string,propertyId:string){const q=await db.query(`UPDATE player_properties SET tenant_name=NULL,monthly_rent_cents=0 WHERE player_id=$1 AND property_id=$2 RETURNING property_id`,[playerId,propertyId]);if(!q.rowCount)throw new RealEstateCommandError('property_not_owned',404);return result(db,playerId,'lease_ended');}
export async function advanceRealEstateCareer(db:Database,playerId:string){await ensureCareer(db,playerId); const c=(await db.query(`SELECT license_stage,employed FROM real_estate_careers WHERE player_id=$1`,[playerId])).rows[0]; if(c.employed)throw new RealEstateCommandError('already_employed',409); if(c.license_stage<2){await db.query(`UPDATE real_estate_careers SET license_stage=license_stage+1,updated_at=now() WHERE player_id=$1`,[playerId]);return result(db,playerId,c.license_stage===0?'licensing_started':'license_awarded');} await db.query(`UPDATE real_estate_careers SET employed=true,updated_at=now() WHERE player_id=$1`,[playerId]);await log(db,playerId,'career','Sol Dorado Realty те нае като Trainee Agent.','Sol Dorado Realty hired you as a Trainee Agent.');return result(db,playerId,'employment_started');}
export async function matchClient(db:Database,playerId:string,clientId:string,propertyId:string){await ensureCareer(db,playerId); const cstate=(await db.query(`SELECT employed FROM real_estate_careers WHERE player_id=$1`,[playerId])).rows[0];if(!cstate.employed)throw new RealEstateCommandError('agent_employment_required',409);const client=CLIENTS.find(c=>c.id===clientId);if(!client)throw new RealEstateCommandError('client_not_found',404);const p=(await db.query(`SELECT id,kind,district,price_cents,parking_spaces FROM real_estate_properties WHERE id=$1`,[propertyId])).rows[0];if(!p)throw new RealEstateCommandError('property_not_found',404);const score=scorePropertyMatch(client,{priceCents:Number(p.price_cents),district:p.district,kind:p.kind,parkingSpaces:p.parking_spaces});if(score>=80){const commission=Math.round(Number(p.price_cents)*0.98*0.05*0.4);await db.query(`INSERT INTO real_estate_client_progress(player_id,client_key,status) VALUES($1,$2,'closed') ON CONFLICT(player_id,client_key) DO UPDATE SET status='closed'`,[playerId,clientId]);await db.query(`UPDATE real_estate_careers SET reputation=LEAST(100,reputation+5),commission_earned_cents=commission_earned_cents+$2 WHERE player_id=$1`,[playerId,commission]);await db.query(`UPDATE player_state SET cash_cents=cash_cents+$2,version=version+1,updated_at=now() WHERE player_id=$1`,[playerId,commission]);await log(db,playerId,'agent_deal',`Успешна сделка с ${client.name}. Комисиона $${Math.round(commission/100)}.`,`Successful deal with ${client.name}. Commission $${Math.round(commission/100)}.`);return result(db,playerId,'client_closed');}if(score>=50){await db.query(`UPDATE real_estate_careers SET reputation=LEAST(100,reputation+1) WHERE player_id=$1`,[playerId]);return result(db,playerId,'client_wants_options');}await db.query(`UPDATE real_estate_careers SET reputation=GREATEST(0,reputation-4) WHERE player_id=$1`,[playerId]);return result(db,playerId,'poor_match');}
